### ISSUE TITLE
Please add me to this organisation/team so that I can start contributing

### ISSUE THREAD

**Issue by davehobbs** [AdoptOpenJDK/openjdk-installer#1]
I'm a member of the IBM Runtimes classes team in Hursley, and would like to contribute to AdoptOpenJDK. I have a particular interest in installers...

[(Following Geraint's how to)](https://github.com/AdoptOpenJDK/openjdk-infrastructure/wiki/How-to-contribute-to-AdoptOpenJDK-Infrastructure)

**Comment by karianna** [comment]
Invited, if you don't see it in your inbox then please check GitHub.
