### ISSUE TITLE
Language JRE AdoptOpenJDK 8 openj9

### ISSUE THREAD

**Issue by burMob** [AdoptOpenJDK/openjdk-installer#101]
Hello,

I've tried to deploy the JRE with openj9. With Orca I've made a transform (but can't find anything to set the language) for our needs.

The downloaded file is OpenJDK8U-jre_x64_windows_openj9_8u212b03_openj9-0.14.0.msi and it install the JRE in chinese language.

How can I change the language to german or english?

br
Marc

**Comment by douph1** [comment]
Hi,

>it install the JRE in chinese language

How are you viewing the JRE is in chinese ?

The only language known by the installer are used for the installer itself when running in interactive mode (GUI)
and is detected from the OS current local.
The available language for the Windows MSI GUI are listed here
https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/wix/Lang/LanguageList.config

As you can see here for exemple, many of the installer label are not translated into chinese at this time.
https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/wix/Lang/OpenJDK.Base.zh-cn.wxl
https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/wix/Lang/OpenJDK.Base.zh-tw.wxl

Here you can find some or all LANGID by country corresponding to our LanguageList.config :
https://docs.microsoft.com/en-us/windows/desktop/msi/localizing-the-error-and-actiontext-tables

The JRE or JDK pakaged into the installer is the same for all country/language.

**Comment by bursped** [comment]
Hi douph1,

>>The only language known by the installer are used for the installer itself when running in interactive
>>mode (GUI) and is detected from the OS current local.

I've now tested it interactive on my PC:
OpenJDK8U-jre_x64_windows_openj9_8u212b03_openj9-0.14.0.msi -> Chinese GUI
OpenJDK8U-jre_x64_windows_hotspot_8u212b03.msi --> German GUI

So there must be a difference in the packages ...

br
Marc

**Comment by douph1** [comment]
C:\Users\adminup>cscript  "c:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\wisubstg.vbs" //Nologo c:\Users\adminup\Downloads\OpenJDK8U-jre_x64_windows_openj9_8u212b03_openj9-0.14.0.msi
1028
1031
1036
1041
2052
3082
Orca show : Property->ProductLanguage: 1033
Orca top menu: Tools :Code Page : Current Code Page 1252

C:\Users\adminup>cscript  "c:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\wisubstg.vbs" //Nologo c:\Users\adminup\Downloads\OpenJDK8U-jre_x64_windows_hotspot_8u212b03.msi
1028
1031
1036
1041
2052
3082

Orca show : Property->ProductLanguage: 1033
Orca top menu: Tools :Code Page : Current Code Page 1252

OpenJDK8U-jre_x64_windows_openj9_8u212b03_openj9-0.14.0.msi select French dialog on my FR-fr desktop

It seems windows installer take the last one added from the LanguageList.config
wich is also the first returned by wisubstg.vbs.

It is probably the default because it didn't match your locale as 1031.
But why for OpenJDK8U-jre_x64_windows_openj9_8u212b03_openj9-0.14.0.msi and not OpenJDK8U-jre_x64_windows_hotspot_8u212b03.msi ... I dont know sorry

You can bypass auto-select language by :

msiexec /i  c:\Users\adminup\Downloads\OpenJDK8U-jre_x64_windows_hotspot_8u212b03.msi TRANSFORMS=:1031

**Comment by douph1** [comment]
You can also try to edit MSI with ORCA and change Property->ProductLanguage to 0 
save
Then recreate *a new generated* MST transform
and test please

**Comment by bursped** [comment]
Hi,

> I've now tested it interactive on my PC:
> OpenJDK8U-jre_x64_windows_openj9_8u212b03_openj9-0.14.0.msi -> Chinese GUI
> OpenJDK8U-jre_x64_windows_hotspot_8u212b03.msi --> German GUI

This happens if the packet is installed in the background. Today I checked it again and get my language by interactive install.

I have tested to set the language to 0, 1031 and 1033. Always the same result:
Interactive-install is in correct language, but deployed by gpo it's chinese.

In the GPO you can see at the produktinformation that the language is chinese (with all language settings above)

**Comment by douph1** [comment]
>This happens if the packet is installed in the background.

So there is no problem I think, it is juste GPO msc wich display you last language referenced inside the installer, but it wont change anything to your installed AdoptOpenJdk wich is not transcripted in multilanguage

>but deployed by gpo it's chinese.
You see chinese in GPO.. but the JDK/JRE is always the same.. so what is the problem ?

The language is only used for the interactive installation, so deployed by the GPO, I dont see any impact possible.

Have you a probleme with the JRE installed ? Malfunction ? Display your java program in chinese ?

**Comment by burMarc** [comment]
>Have you a probleme with the JRE installed ? Malfunction ? Display your java program in chinese ?

No, but the chinese installer-gui is a problem for our technicans if they have to repair something manually at the clients

**Comment by douph1** [comment]
Is Ojdkbuild a multi-language installer ?

**Comment by douph1** [comment]
> Is Ojdkbuild a multi-language installer ?

It seem's no, I dont have french setup UI. So it is not comparable to AdoptOpenJdk installer

To fall back to your problem:
>No, but the chinese installer-gui is a problem for our technicans if they have to repair something manually at the clients

You mean you deploy by GPO successfully but if you log into client computer and go to "Add or remove programs" and clic "Modify" for interactif UI "repair" and here you get installer in Chinese right ?

**Comment by burMob** [comment]
> You mean you deploy by GPO successfully but if you log into client computer and go to "Add or remove programs" and clic "Modify" for interactif UI "repair" and here you get installer in Chinese right ?

yes

**Comment by douph1** [comment]
1) Language :

>but can't find anything to set the language) for our needs.

I can't test by deploying with Active Directory but tested to select language with msiexec.

You must apply ***internal*** transform present in MSI to choose language as stated here https://docs.microsoft.com/en-us/windows/desktop/msi/transforms

>You can indicate that a transform file is embedded in a storage of the .msi file, rather than as a stand-alone file, by prefixing the filename with a colon (:).

`TRANSFORMS=:1031`

![language_only](https://user-images.githubusercontent.com/45632394/57214038-e82efc80-6fe8-11e9-97ff-06ed89f1d083.png)


2) Transform to add/remove features
You can mix Language selection with your custom transform to add or remove other feature present in the msi.

I tried and works great with msiexec on my local french computer. Setup is done silently in german ( can see "mit" in "Add or remove program" and "edit" or "remove" gui is in german.

! If you add external transform file, you can't edit anymore ( repair ). Only "install" button is available and probably do nothing

![german_und_mst](https://user-images.githubusercontent.com/45632394/57214065-08f75200-6fe9-11e9-8fd7-fc18a0c247ae.png)


To create a transform MST for features selection : 
With ORCA : 
Open MSI:
* Transform -> New Transform

* Always include "FeatureMain" ( required ), "FeatureMain" require a path where to install AdoptOpenJdk : set "INSTALLDIR" variable with a path
* add you other features

Then 
* Transform -> Generate Transform...
* Transform -> Close Transform
* File -> Exit

sample to enable all features :
![msi_transform](https://user-images.githubusercontent.com/45632394/57214287-d568f780-6fe9-11e9-8e79-a919f5a08d9f.png)

**Comment by burMob** [comment]
> I have tested to set the language to 0, 1031 and 1033. Always the same result:
> Interactive-install is in correct language, but deployed by gpo it's chinese.

This was already a test with transforms

**Comment by douph1** [comment]
https://success.trendmicro.com/solution/1059376-arabic-language-appears-when-deploying-the-worry-free-business-security-services-wfbs-svc-msi-agen

>with a Group Policy, the language values are read according to the numerical order of the available languages in the MSI package

https://www.itninja.com/blog/view/how-to-update-gpo-kace-agent

>you need to run a script to change the language of the MSI to English. You can download the script HERE.

https://forums.zimbra.org/viewtopic.php?t=43681
(with ORCA)
>You can open the MSI with it, under view --> Summary Information go to the Languages input field and remove all but 1033. Okay and save. Pretty simple!

**Comment by burMob** [comment]
it works to remove the other languages with orca
