### ISSUE TITLE
rpm package for fedora 30

### ISSUE THREAD

**Issue by stbischof** [AdoptOpenJDK/openjdk-installer#102]
Upgrade package for fedora Version 30.

https://github.com/AdoptOpenJDK/openjdk-installer/blob/8933422f46560eff2f3a3445c33adc246584522a/linux/rpm/build.gradle#L71

**Comment by aahlenst** [comment]
Thanks for the report. I already made the necessary changes. They are waiting for the PR queue to clear.

Just FYI: Building is not affected by this, only distribution and the package feeds aren't public yet. You can happily build packages for Fedora 30 without any changes.
