### ISSUE TITLE
install per user without elevated privilege

### ISSUE THREAD

**Issue by Eskibear** [AdoptOpenJDK/openjdk-installer#103]
I'm using AdoptOpenJDK's MSI installer. For some reason, I don't have elevated privilege of the windows machine. 

**Is there any way (besides extracting ZIP by my own) to install it?**

![adoptopenjdk_admin](https://user-images.githubusercontent.com/2351748/57190483-38f11780-6f4d-11e9-90ff-a80526335fc5.gif)

**Comment by douph1** [comment]
>Is there any way (besides extracting ZIP by my own) to install it?

The installation currently runs with ALLUSERS=1 to install in a per-machine context, meaning only one installation of the MSI is allowed on the machine for all users.

No, MSI is designed to install in a per-machine context, meaning only one installation of the MSI is allowed on the machine for all users.

Main installation write to HKLM registry keys to remember folder to remove on uninstall

**Comment by karianna** [comment]
@douph1 Is there a reason why we went for the _per machine_ as opposed to _per user_ installation?

**Comment by douph1** [comment]
I don't know, I have just write down the actual state.
All is designed to work per machine from begining.

some interesting hint
https://www.indigorose.com/webhelp/sufwi/Concepts/Per-Machine_vs._Per-User_Installations.htm

If really needeed, there is a lot to re-think..
MSI Upgrade ( will work or not ? )
Per user PATH and JAVA_HOME .. and what to do if installer by administrator ..
Per user jar file association
I think JavaSoft key don't exist per user.
and comming 
ITW integration per user
Update notifier per user

Actually the only real possibility is : be admin or use zip file and set PATH/JAVA_HOME yourself

PS: we don't provide .deb ou macOsX installer per user I think :)
