### ISSUE TITLE
Investigate shipping smaller deb/rpm packages

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-installer#106]
The draft packages (deb/rpm) of AdoptOpenJDK bundle the entire JDK. This is size-wise a problem for people that want their Docker images to be as small as possible.  

Current situation on CentOS 7 (it's the same on other distributions): `adoptopenjdk-11-hotspot` comes in at around 310 MB. `java-11-openjdk-headless` provided by CentOS 7 weighs around 38 MB. Two big drivers for this difference are `lib/src.zip` (~58 MB) and the jmods (~80 MB) which are only necessary if you want to produce custom images with jlink.

Big question: Do we want to address this problem or just tell the people to use jlink?

If we want to address this problem, I see two possible ways forward (maybe there are more):

1. Follow the path of the AdoptOpenJDK Docker images and produce `slim` packages of the JRE and JDK.
2. Split the AdoptOpenJDK Deb and RPM packages like the Linux distributions do (but not to the exact same extent), i.e. move `lib/src.zip` and the jmods into separate packages.

Option 1 should yield the biggest weight savings because we can aggressively remove things.

**Comment by nudgegoonies** [comment]
Headless packages are a good thing in reducing dependencies for server side applications. But they can also make trouble. One example from our work was a server side application whose library needed the Non-Headless libraries only for calculating Font sizes for its generated HTML/CSS.

In OpenJDK the split between Headless/Non-Headless is done by separating frontend Java libraries in own packages (the ones without -headless in the name). And only these packages require the Xorg dependencies for example which make a big difference in size.

AdoptOpenJDK has a lot of libraries bundled while the OpenJDK packages in the Linux distributions depend on distribution libraries. I don't know the AdoptOpenJDK Build process from it's sources but i think these libraries are supplied for (TCK) compatibility. With these libraries AdoptOpenJDK headless packages would stil be bigger than the OpenJDK ones.

The naming convention is also interesting. Actually there is adoptopenjdk-$VERSION-$JVM[-$JRE] where the -jre is optional. It breaks the "explicit is better than implicit" paradigm for a JDK but it works. To not break the actual names the -headless should be optional too. For example:
adoptopenjdk-11-hotspot
adoptopenjdk-11-hotspot-headless
adoptopenjdk-11-hotspot-jre
adoptopenjdk-11-hotspot-jre-headless
adoptopenjdk-11-openj9
adoptopenjdk-11-openj9-headless
adoptopenjdk-11-openj9-jre
adoptopenjdk-11-openj9-jre-headless

**Comment by nudgegoonies** [comment]
I took a look in the AdoptOpenJDK 11 lib folder and found these two files:
libawt.so
libawt_headless.so
The headless variant is much smaller. I compared the dependencies and most of the dependencies are the same. But libawt_headless has more dependencies than libawt. And the strange thing is that one of these dependencies is libawt. The other one is even more strange as this is libjvm.

**Comment by aahlenst** [comment]
Unlikely that we'll do this. It's not something that's supported by upstream, it's a lot of work to untangle everything, and if size is at a premium, users shouldn't use a JDK anyway but rather a jlink'ed runtime.
