### ISSUE TITLE
RPM  package for amazonlinux

### ISSUE THREAD

**Issue by jordanst3wart** [AdoptOpenJDK/openjdk-installer#116]
Hi, 
Is it possible to produce a RPM for amazonlinux/amazonlinux2? 

It should be very similar to the Centos /  Redhat.

Relates to:
#26

**Comment by gdams** [comment]
@aahlenst

**Comment by jordanst3wart** [comment]
Thank you!

**Comment by aahlenst** [comment]
Because there's https://hub.docker.com/_/amazonlinux this shouldn't be a problem. Might take a few days.

**Comment by karianna** [comment]
@aahlenst I've invited you to the team/org BTW so you can self assign issues
