### ISSUE TITLE
The repo for Fedora 30 doesn't work

### ISSUE THREAD

**Issue by cold-distance** [AdoptOpenJDK/openjdk-installer#118]
Hi, I'm trying to install AdoptOpenJDK on Fedora 30, but the repo doesn't work.

I created with sudo the file `/etc/yum.repos.d/adoptopenjdk.repo` with this content:

```
[AdoptOpenJDK]
name=AdoptOpenJDK
baseurl=http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/fedora/30/$(uname -m)
enabled=1
gpgcheck=1
gpgkey=https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
```

When I execute "sudo dnf check-update" or try to install AdoptOpenJDK the system discards the repo and says it can't sync it.

I don't know what I'm doing bad. I think its a repository problem.

**Comment by cold-distance** [comment]
I don't use Docker. I need a solution for a "real" system installed on VirtualBox. I need admin rights to set the repo.

I took the steps from [here](https://medium.com/adoptopenjdk/adoptopenjdk-rpm-and-deb-files-7003ba38144e) and the repo for Ubuntu and Debian works correctly, but I can't say the same thing about Fedora 30.

![Captura de pantalla de 2019-05-21 19-45-46 (copia)](https://user-images.githubusercontent.com/43167050/58119037-68b54600-7c02-11e9-9feb-35591761b003.jpg)

**Comment by aahlenst** [comment]
Your `adoptopenjdk.repo` should look like this:

```
[AdoptOpenJDK]
name=AdoptOpenJDK
baseurl=http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/fedora/30/x86_64
enabled=1
gpgcheck=1
gpgkey=https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
```

The problem with your `adoptopenjdk.repo` is that it still contains `$(uname -m)`.

**Comment by reinhapa** [comment]
The general way to have a dynamic repo working for the current version and arch would look like this:
```
[adoptopenjdk]
name=AdoptOpenJDK $releasever - $basearch
baseurl=http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/fedora/$releasever/$basearch
enabled=1
gpgcheck=1
gpgkey=https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
```

Not that the repo id would be in lower case as standard (but works also in camel case 😎)

**Comment by karianna** [comment]
Sounds like this can be closed.  Please do reopen if the suggestions above aren't adequate!

**Comment by cold-distance** [comment]
Now it's working. Thank your very much.
