### ISSUE TITLE
Windows installer content type register entry

### ISSUE THREAD

**Issue by ldebello** [AdoptOpenJDK/openjdk-installer#119]
Hi guys, 

This is more a question than an issue, some of our customers start using AdoptOpen JDK in windows and they report some issue when loading a jar in our platform, after some debugging we realized that before uploading the UI (Javascript code) validate the mime type if present, we have some hardcoded mime type but the more common seems application/java-archive , we noticed the installer configure the mime type to be application/jar, giving the fact we were not taking that value into account we rejected the file.

My question is why you have choose application/jar I looked in different places to ser if this was some standard, or defined in IANA but I didnt find anything, as far as I know we use application/java-archive because at the time of the development was the most widthly used also I think tomcat define that mime type for jar files.

https://github.com/AdoptOpenJDK/openjdk-installer/blob/c7dc8f6c71a11bfdfbeef329ab951b66b393414b/wix/Main.hotspot.wxs#L127

Also I think about Java 7 and the method Files.probeContentType which I think the implementation is platform dependent so I am assuming (because I didnt test it) in this case will return the same value from the registry. Which could be ok but at the same type the installer could be breaking other apps.

Regards,
Luis

**Comment by douph1** [comment]
Hi, @ldebello 
you'are right, it seems to be an error.
I will change it soon

**Comment by gdams** [comment]
ping @douph1 any update on this?
