### ISSUE TITLE
OpenJDK 11 on MacOsx Mojave

### ISSUE THREAD

**Issue by ppkabore** [AdoptOpenJDK/openjdk-installer#122]
Hi,

  I have installed openjdk 11 on my Mac and found myself unable te use another java version. It has been installed in the /System/Library directory (and in the /Library/Frameworks as well, like for Oracle JDK). Now I cannot unlink /usr/bin/java nor the link in the installation directory to point to another java version. What to do if I wZnty to switch versions or uninstall openjdk 11.

Thans for your help.

**Comment by karianna** [comment]
https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-os-x has some common techniques to move between versions.
