### ISSUE TITLE
AdoptOpenJDK installers do not remove their registry keys from JavaSoft on uninstall

### ISSUE THREAD

**Issue by 1spiderlily** [AdoptOpenJDK/openjdk-installer#124]
Using AdoptOpenJDK installers (JDK or JRE), if you select the option to JavaSoft (Oracle) registry keys to the HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft, and then uninstall AdoptOpenJDK  (JRE or JDK), the keys that were added are not removed.

**Comment by douph1** [comment]
You probably have antother installer which handle this key too
Msi work like that .. is only one installer reference the same reg key, they won't be delete until all msi where removed.

Can you confirm that you have another openjdk or Oracle installed ?

**Comment by 1spiderlily** [comment]
duoph1,

I did have Oracle Java installed as well, but I expected that AdoptOpenJDK would remove its 8.0.212.3 key.  Software we create looks here to find the latest version of Java installed, and it may find AdoptOpenJDK's key, however it is no longer installed.  See attached image for the key I'm talking about.

![AdoptOpenJDK_JRE_registry](https://user-images.githubusercontent.com/51134088/58506073-76b41b00-815c-11e9-821c-23afde3d4878.png)

**Comment by douph1** [comment]
All the keys under JavaSoft are managed by one component from the Adopt installer.
"CurrentVersion" is the same key for Oracle and Adopt

I think Windows installer work like this : If he can't remove all because some are shared (CurrentVersion) by Oracle msi, it will not remove any.

**Comment by 1spiderlily** [comment]
Thanks.  This does create a problem for some software that uses Java, though.  I can write installers that remove their subkeys without removing the parent key.

**Comment by douph1** [comment]
removing the sub key is not needed. You can do it to clean up but if CurrentVersion is not pointing to it , it will not be used.

**Comment by douph1** [comment]
The more important part is to recover CurrentVersion to pointing to Oracle version as before if you keep both.
This is a know problem documented in readme
https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/wix/README.md

**Comment by douph1** [comment]
I close it because it is the Windows Installer intenal functionnality to not remove a shared reg key registered by more than one msi.
If you find a way to overload this fonctionnality from MSI or find a workaround, please open a new issue/feature
