### ISSUE TITLE
Missing provides in debian dependencies

### ISSUE THREAD

**Issue by nudgegoonies** [AdoptOpenJDK/openjdk-installer#126]
OpenJDK has non-headless and headless packages. They deduplicate as much as possible and so their jdk and jre packages depend on their jdk-headless and jre-headles counterparts and the jdk and jre packages only add the graphic libraries and add Xorg dependencies for them. AdoptOpenJDK does not build headless packages. Because the packages always include the graphic libraries and dependencies they mus not only provide the headless packages but also the non-headless packages.

We had bug with a package that required java8-runtime that could not be installed with adoptopenjdk.

See my MR here: https://github.com/AdoptOpenJDK/openjdk-installer/pull/125

**Comment by aahlenst** [comment]
Thanks for the pull request and the report. If you create a pull request anyway, you don't have to open a separate issue (at least from my point of view).

**Comment by nudgegoonies** [comment]
Ok, this differs from project to project. On Github, Gitlab, an internally in my Company :-) For me it is also OK to only open a pull request. My notification settings match that.
