### ISSUE TITLE
how to uninstall or upgrade?

### ISSUE THREAD

**Issue by tessus** [AdoptOpenJDK/openjdk-installer#134]
I'm really sorry to open a ticket, but I have searched the web site, different issue trackers, but couldn't find a single document that describes how to uninstall AdoptOpenJDK.

I've installed OpenJDK8U-jdk_x64_mac_hotspot_8u212b04.pkg

I have 2 questions:

- How do I uninstall it from my system?
- What would I have to do, if I wanted to upgrade to Java 11 or install a version with OpenJ9?

**Comment by karianna** [comment]
@tessus Hopefully this helps 

https://superuser.com/questions/36567/how-do-i-uninstall-any-apple-pkg-package-file

For upgrade or further installations, you need to run their respective pkg's or use homebrew.

**Comment by tessus** [comment]
@karianna Thanks for the reply. Well, I knew how to remove .pkg files, but it is a manual and sometimes rather dangerous process. That is why I hoped there would be an uninstall script or the steps for removing specifically your package on the web site.
You really show give people some information on how to remove it.

> For upgrade or further installations, 

What is it? upgrade or additional install? These are two different things.
According to your statement it seems that there's no upgrade. Installing a package will always install a new Java. If this is not the case, what is the criteria?

I'm a bit puzzled by the fact that even though AdoptOpenJDK is an alliance that includes pretty big players, the documenttion is rather sparse. I don't really want to figure all this stuff out by trial and error.

How complicated is it to have 3 sections that cover the following 3 items:

- uninstall
- upgrade
- install of an additional package

I can't believe I'm the only one who ever brought this up.

**Comment by karianna** [comment]
@tessus Unfortunately the Mac OS X ecosystem is pretty poor on uninstallers in general (I know that I usually just drag an Application to the Trash to remove something).

A majority of our Mac OS X users use Homebrew to install and then upgrade their AdoptOpenJDK binaries (for example 8u202 --> 8u212) and installing major versions alongside each other (for example, 8u212-b04 and 11.0.3+7).

For managing installations and versions manually I'd recommend the following post:

https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-os-x

----

AdoptOpenJDK is a fairly new community and we still have documentation improvements to make!  But to be clear, AdoptOpenJDK has never been about the 'large vendors providing everything for free' it's about the entire Java community pitching in together!  You can submit pull-requests to improve our website docs at our openjdk-website repo, would be great to have a new user's perspective!

**Comment by tessus** [comment]
@karianna Thanks again for the info.

Yes, I am aware of how to run several Java versions in parallel. I'm just not so sure about the package installer activity. So installing a newer version of the same release will upgrade it and installing a newer release will install it next to the other one? These are questions that have to be answered by the guys who created the installers. I don't want to mess up my system for testing this.

But I will take notes as I go along and when I have some useful info, I will create a PR in the website repo.

e.g. info on how to properly uninstall is certainly useful, because after I install another LTS, I don't want to keep the old one on my system. maybe creating an uninstall bash script could help. If I find a proper procedure to uninstall Java from macOS, I will open a PR here to add a bash uninstaller script.

**Comment by karianna** [comment]
Thanks!

**Comment by FranklinYu** [comment]
After reading the conversation above, I decide to simply use [Homebrew Cask](https://github.com/AdoptOpenJDK/homebrew-openjdk) to prevent messing up my Mac. Note that it's the official Homebrew tap so it should be reliable.

**Comment by tessus** [comment]
@FranklinYu luckily I don't need Java very often, thus I hadn't had the time to link into writing an uninstall script. Which in my opinion should be mandatory for all apps that don't  install  just in  `/Applications`. I use MacPorts and I definitely won't use brew additionally to that.

But I hope I will find some time to write a nice uninstall script...

**Comment by FranklinYu** [comment]
@tessus I’m also using MacPorts in my personal Mac, and I have migrated to [`openjdk11`](https://www.macports.org/ports.php?by=library&substr=openjdk11) (actually AdoptOpenJDK despite the name) avoiding those PKGs altogether. In contrast my employer prefers Homebrew, so I manage the Java versions on those Mac minis with Homebrew.

**Comment by wonjoonSeol** [comment]
adoptopenjdk.net should really just tell mac users to use homebrew instead of letting us download pkg files...

**Comment by karianna** [comment]
> adoptopenjdk.net should really just tell mac users to use homebrew instead of letting us download pkg files...

Mac Os X users have told us they prefer the choice :-)

**Comment by tessus** [comment]
@wonjoonSeol 

>  tell mac users to use homebrew instead

I use MacPorts, so telling macOS users to use something they are not using which requires them to use yet another portage system would not sit very well with them - it certainly wouldn't with me.

**Comment by FranklinYu** [comment]
How about *adding* a note that they can also use Homebrew? Now that Homebrew is officially supported, its situation is different from MacPorts (or any other package manager).

**Comment by Karamvir-Singh** [comment]
Did anyone write an uninstall script or simply a guide to completely uninstall it yet. I still cannot find it and reading through this thread doesn't provide any of the two.

**Comment by aahlenst** [comment]
Locate the version you want to delete in `/Library/Java/JavaVirtualMachines/`, delete the directory (for example, `/Library/Java/JavaVirtualMachines/adoptopenjdk-8`) and you're done.

Yes, we are aware that a user guide is desperately needed.

**Comment by Sajaki** [comment]
if you install it using brew then uninstalling it would just be done using brew remove.
https://github.com/AdoptOpenJDK/homebrew-openjdk
