### ISSUE TITLE
Installer issues with OpenJDK 8 on Debian 10 Buster

### ISSUE THREAD

**Issue by energy-cloud** [AdoptOpenJDK/openjdk-installer#147]
Please raise an issue at https://github.com/AdoptOpenJDK/openjdk-installer or https://github.com/AdoptOpenJDK/homebrew-openjdk if it's an issue with our brew casks

Following install instructions here: https://adoptopenjdk.net/installation.html#linux-pkg
but it's failing on install.

OS
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

Issues happen even when running the following first:
sudo apt-get install -y software-properties-common
________________________________
sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/

Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster
_____________________________________

**Comment by energy-cloud** [comment]
Thanks,  If you can please let me know when the armhf version is done, I would appreciate it.

**Comment by aahlenst** [comment]
armhf is done for JDK 8, 11 and 12 with Hotspot. OpenJ9 needs another moment. You can track the progress in https://github.com/AdoptOpenJDK/TSC/issues/105.

**Comment by energy-cloud** [comment]
Thank you.

-John

**Comment by rfm1** [comment]
after adding OpenJDK entry to sources.list,

        deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main

sudo apt update gives the following errors

>root@localhost:/etc/apt# sudo apt update
>Hit:1 http://deb.debian.org/debian buster InRelease
>Hit:2 http://deb.debian.org/debian-security buster/updates InRelease
>Hit:3 http://deb.debian.org/debian buster-updates InRelease
>Get:4 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease [6,155 B]
>Err:4 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease
>  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY >8AC3B29174885C03
>Reading package lists... Done
>W: GPG error: https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8AC3B29174885C03
>E: The repository 'https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease' is not signed.
>N: Updating from such a repository can't be done securely, and is therefore disabled by default.
>N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by karianna** [comment]
@aahlenst Is that expected this time around?

**Comment by aahlenst** [comment]
This isalways expected if you don't install our public key which seems to be the case according to the error message:

> The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 

`wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -` helps.

**Comment by rfm1** [comment]
Thank you for your response.

Here's what I don't get: if it is "always expected" how is it that it is 
not part of any install instructions that I've read?  Wouldn't that 
addendum be obvious?

**Comment by aahlenst** [comment]
> Here's what I don't get: if it is "always expected" how is it that it is not part of any install instructions that I've read?

Question is: What did you read? https://blog.adoptopenjdk.net/2019/05/adoptopenjdk-rpm-and-deb-files/ lists it, for example. https://adoptopenjdk.net/installation.html#linux-pkg does, too (1st step).

**Comment by rfm1** [comment]
I cut/pasted the syntax you gave.  This is what was returned:
>root@localhost:/lib/jvm# wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
>E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation

**Comment by rfm1** [comment]
I'm sorry that I'd closed the webpage that laid out the step-by-step or I certainly would pass it along.
Update: I found the gnupg package in synaptic, installed it, then reran the wget and it returned OK.  Now let's see if all these machinations will actually allow me to install the package I'd wanted in the first place (not your problem)..  Thanks for your help.
