### ISSUE TITLE
Windows: Selected install path is ignored

### ISSUE THREAD

**Issue by bmaehr** [AdoptOpenJDK/openjdk-installer#148]
When selecting a path different to C:\Program Files\AdoptOpenJDK to install the jdk to the selection is ignored and the jdk is installed to C:\Program Files\AdoptOpenJDK.

Happend on 8, 11 an 12.

**Comment by gdams** [comment]
@bmaehr are you using the command line installer or the gui?

**Comment by bmaehr** [comment]
I installed them with the GUI.

**Comment by gjabouley-invn** [comment]
For information, it seems to work fine for the JRE installer...

**Comment by douph1** [comment]
Tested with OpenJDK8U-jdk_x64_windows_hotspot_8u222b10.msi
Default folder sugested : C:\Program Files\AdoptOpenJDK\jdk-8.0.222.10-hotspot\

**Comment by douph1** [comment]
Can you provide detailed log about installation steps by enabling verbose logging ?:
 >msiexec /i OpenJDK8U-jdk_x64_windows_hotspot_8u222b10.msi /l* install.log

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback.
