### ISSUE TITLE
how does the IcedTeaWebBin come from?

### ISSUE THREAD

**Issue by BIG-CHEF** [AdoptOpenJDK/openjdk-installer#155]
you will get 3 bat scripts(javaws.bat, policyeditor.bat, itweb-settings.bat) after compiling IcedTea-Web, how does the bin file come from?

**Comment by douph1** [comment]
Hi,
bat script are for IcedTeaWeb 1.7 and older
bin are for 1.8 and newer
1.7 is deprecated

You can find some hint here to build 1.8 branch : https://github.com/AdoptOpenJDK/IcedTea-Web/issues/313

You must use:
autogen
configure
make

Build script from Adopt :

`echo ${ICEDTEAWEB_VERSION}
echo "Temporarily add rustc to path until machine config is changed"
export WIXPATH="$(cygpath -u "C:/PROGRA~2/WIXTOO~1.11/bin")"
export WIXGEN="$(cygpath -u "C:/cygwin64/usr/share/java/wixgen.jar")"
export PATH="${PATH}:/cygdrive/c/rust/bin:${WIXPATH}"
export JVM_HOME_SHORT="$(cygpath -d "${JAVA_HOME}")"
export JVMPATH="$(cygpath -u ${JVM_HOME_SHORT})"
export ICEDTEAWEB_INSTALL="$(cygpath -u "${WORKSPACE}/icedtea-web-image")"

cd "icedtea-web"
echo "Configure IcedTea-Web"
./autogen.sh
./configure --disable-native-plugin --prefix="${ICEDTEAWEB_INSTALL}" --with-wix=${WIXPATH} --with-wixgen=${WIXGEN} --with-itw-libs=BUNDLED --with-jdk-home="${JVMPATH}"

export RUSTFLAGS="-C target-feature=+crt-static"

echo "Build IcedTea-Web"
make

if [ "${BUILD_DISTRIBUTION}" = true ]; then
	echo "Create IcedTea-Web Distribution"
	make win-bin-dist
    find . -name "icedtea-web-*.win.bin.zip"
fi

if [ "${BUILD_INSTALLER}" = true ]; then
	echo "Create IcedTea-Web MSI"
	make win-installer
    find . -name "icedtea-web-*.msi"
fi
`

**Comment by BIG-CHEF** [comment]
the answer is helpful, i noticed that adoptopenjdk8 includes IcedTea-Web bin files, is IcedTea-Web 1.8 adaptable for JDK8?

**Comment by BIG-CHEF** [comment]
or IcedTea-Web 1.8 is just for JDK 11 and newer

**Comment by douph1** [comment]
ITW 1.8 is bundled with AdoptOpenJDK8 because it is the latest final release available
So Yes it work with JDK8.
