### ISSUE TITLE
Artifactory APT Debian Package Repository Index broken

### ISSUE THREAD

**Issue by nudgegoonies** [AdoptOpenJDK/openjdk-installer#168]
Reproduce in Container with following repository:
```
deb https://adoptopenjdk.jfrog.io/adoptopenjdk/list/deb/ buster main
```
apt update gives:
```
Get:36 https://adoptopenjdk.jfrog.io/adoptopenjdk/list/deb buster/main amd64 Packages [5232 B]
Fetched 8710 kB in 3s (2992 kB/s)                          
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/adoptopenjdk.jfrog.io_adoptopenjdk_list_deb_dists_buster_main_binary-amd64_Packages.lz4
E: The package lists or status file could not be parsed or opened.
```

**Comment by nudgegoonies** [comment]
Maybe a

**Comment by aahlenst** [comment]
Yep, I hit the button. And I have to talk to JFrog. This happens more often than not.

Please reopen if the problem persists. I cannot check it myself at the moment.

**Comment by nudgegoonies** [comment]
Thank you very much. Now it works again.

We have lots of packages in our internal APT Package Repository on our internal Artifactory instance. It already happened on our instance too too but because there are lots of uploads it recalculates the index more often automatically.
