### ISSUE TITLE
Ubuntu installation failed with "Problem with MergeList "

### ISSUE THREAD

**Issue by woj-tek** [AdoptOpenJDK/openjdk-installer#169]
I wanted to install/update AdoptOpenJDK and after following the instructions on https://adoptopenjdk.net/installation.html?variant=openjdk11&jvmVariant=hotspot# I run into following error:
```
Fetched 18.9 MB in 6s (2,939 kB/s)
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/adoptopenjdk.jfrog.io_adoptopenjdk_deb_dists_xenial_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```

I tried removing the lists with `sudo rm /var/lib/apt/lists/* -vf` and updating again but it didn't work. I removed the PPA, cleared the lists, clean apt-get and it worked this time

**Comment by aahlenst** [comment]
Repository has been re-indexed. Should be good now.
