### ISSUE TITLE
Artifactory APT Debian Package Repository Index broken

### ISSUE THREAD

**Issue by nudgegoonies** [AdoptOpenJDK/openjdk-installer#172]
This week stretch is broken. Same error as last week:
https://github.com/AdoptOpenJDK/openjdk-installer/issues/168
https://github.com/AdoptOpenJDK/openjdk-installer/issues/169
Please recalculate index again!

**Comment by aahlenst** [comment]
Done

**Comment by nudgegoonies** [comment]
I checked all 3 debians and they work (jessie, stretch, buster).
