### ISSUE TITLE
Latest adoptopenjdk 8 hotspot package has lower version number

### ISSUE THREAD

**Issue by nudgegoonies** [AdoptOpenJDK/openjdk-installer#174]
Sorry to bother you again. But i cannot update to the latest version of adoptopenjdk with buster. This package is not available:
https://adoptopenjdk.jfrog.io/adoptopenjdk/webapp/#/artifacts/browse/tree/Properties/deb/pool/main/a/adoptopenjdk-8-hotspot/adoptopenjdk-8-hotspot_1.8.0_232-b09-2_amd64.deb
The highest version i see with apt-cache policy is this:
https://adoptopenjdk.jfrog.io/adoptopenjdk/webapp/#/artifacts/browse/tree/Properties/deb/pool/main/a/adoptopenjdk-8-hotspot/adoptopenjdk-8-hotspot_8u222-b10-2_amd64.deb
Both have similar properties except one Ubuntu release name. Both have the buster property so they should be available in buster. This is strange, because i find the package in the indexfile:
https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/buster/main/binary-amd64/Packages

**Comment by nudgegoonies** [comment]
Found it. There is a problem with the version. I forgot to look at the bottom of the "apt-cache policy" output. The new version is much lower then the versions before:
```
apt-cache policy adoptopenjdk-8-hotspot
adoptopenjdk-8-hotspot:
  Installiert:           8u222-b10-2
  Installationskandidat: 8u222-b10-2
  Versionstabelle:
 *** 8u222-b10-2 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
        100 /var/lib/dpkg/status
     8u212-b04-2 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
     8u212-b03-1 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
     1.8.0-232-b09-2 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
```
The new versioning schema breaks it. 1.8.* will always be lower than 8u*!

**Comment by aahlenst** [comment]
I'm very sorry about that. Packages with the correct version numbering have been uploaded.

**Comment by nudgegoonies** [comment]
Thank you. Works fine now.
