### ISSUE TITLE
Uninstall AdoptOpenJDK from Mac

### ISSUE THREAD

**Issue by andrew00077** [AdoptOpenJDK/openjdk-installer#187]
Hello,

How to uninstall properly AdoptOpenJDK from MacOS Catalina? I installed it with the package OpenJDK11U-jdk_x64_mac_hotspot_11.0.6_10.pkg

Is it enough to delete the folder /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk from the system? Is a script to uninstall already released?

Many thanks.

**Comment by aahlenst** [comment]
`rm -rf /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk` is sufficient. You might need to prepend `sudo`.

**Comment by joystick** [comment]
> rm -rf /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk

The command above is not applicable in my case. After running it I have:

➜  ~ java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
➜  ~ which java
/usr/bin/java
➜  ~ ll /usr/bin/java
-rwxr-xr-x  1 root  wheel   136K Jan  1  2020 /usr/bin/java
➜  ~ ll /usr/bin/javac
-rwxr-xr-x  1 root  wheel   136K Jan  1  2020 /usr/bin/javac
➜  ~ ll /usr/bin/javaws 
-rwxr-xr-x  1 root  wheel   136K Jan  1  2020 /usr/bin/javaws
➜  ~

Macos Big Sur

**Comment by aahlenst** [comment]
> The command above is not applicable in my case.

Because it deletes AdoptOpenJDK 11, not 15. For 15, you obviously have to do `rm -rf /Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk`

The programs in `/usr/bin` need to stay, however, because they are provided by macOS.
