### ISSUE TITLE
"Malformed input, repository not added."

### ISSUE THREAD

**Issue by DaniSheng** [AdoptOpenJDK/openjdk-installer#190]
When I try add repository : 
sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
"Malformed input, repository not added."
Linux Mint 19.3

**Comment by aahlenst** [comment]
The problem is that we don't provide separate package feeds for Mint and all its flavours, therefore the automatic detection does not work. Considering that it's a Ubuntu derivative, I'd try with the Debian/Ubuntu packages (they are the same). According to the internet, Linux Mint 19.3 is essentially a respin of Ubuntu 18.04 (Bionic Beaver), so this command should do: 

`sudo apt-add-repository 'deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bionic main'`

**Comment by DaniSheng** [comment]
Working with little one change
`sudo apt-add-repository deb 'deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bionic main'`

But is not installing nothing.

```
sudo apt-get install adoptopenjdk-8-hotspot-jre
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package adoptopenjdk-8-hotspot-jre
```

I don't know what I can do to solve this. Thank You for try help me.

**Comment by aahlenst** [comment]
Did you run `apt update` beforhand? `apt search adoptopenjdk` lists the packages that are installable.

**Comment by DaniSheng** [comment]
Yes, and no appears nothing. I can install via deb files, and show it, and remove it after, but I can not installing via repository.
I checked source list and not is added repository, no accept add it still. Same without error warning.

**Comment by aahlenst** [comment]
Tried in container `linuxmintd/mint19.3-amd64`:

```
$ wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
$ echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bionic main" | sudo tee /etc/apt/sources.list.d/adoptopenjdk.list
$ sudo apt update
$ sudo apt install -y adoptopenjdk-8-hotspot-jre
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```

**Comment by DaniSheng** [comment]
YES!, This time working nice, Thank You!
UBUNTU, Working:
`sudo apt-add-repository 'deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bionic main'`
Linux Mint 19.3, Working:
`echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bionic main" | sudo tee /etc/apt/sources.list.d/adoptopenjdk.list`
Thank You!
