### ISSUE TITLE
Install multiple JDK8 minor versions on Mac

### ISSUE THREAD

**Issue by nikhilahuja** [AdoptOpenJDK/openjdk-installer#193]
Is there a way to install multiple JDK8 minor versions on Mac. For example, I want to have jdk8u192 as well as jdk8u242 installed on my Mac.

Multiple Major JDK versions can be installed as mentioned here: https://stackoverflow.com/questions/26252591/mac-os-x-and-multiple-java-versions

**Comment by gdams** [comment]
The only way I could see this working would be to download the binaries and them in your PATH. Unfortunately adding the minor version to the directory would be considered a breaking change as many users this schema
