### ISSUE TITLE
help

### ISSUE THREAD

**Issue by joeheb1970** [AdoptOpenJDK/openjdk-installer#194]
can you please help me......not spam.....not scam......i need my daughter and am literally going crazy not being able to get back up.......tried absolutely eveyrhting......this is like my last hope.
Its her sixth birthday, March 4 th.....i already missed her 5th....
please guys if there is anything in the world.........i have no phone.....no pc........i work at a labor ready place making $14/hr........and theres no altrenatives.......please help me......
i really cant lose my baby,

**Comment by smlambert** [comment]
Closing as spam and will block further content from this github id
