### ISSUE TITLE
Artifactory indices for xenial busted again

### ISSUE THREAD

**Issue by Nirgali42** [AdoptOpenJDK/openjdk-installer#202]
Artifactory indices for xenial busted again. Can't install on xenial at the moment.

https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/xenial/InRelease

File not found

E: Failed to fetch https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/xenial/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by aahlenst** [comment]
Index has been rebuilt.

I do not understand how that happened. We haven‘t pushed any packages lately.
