### ISSUE TITLE
Windows installer build failling if Jenkins artifact name is not as expected

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/openjdk-installer#207]
./CreateSourceFolder.AdoptOpenJDK.ps1 look zip filename to find which jdk/jvm/arch version this artifact is.

The job https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-hotspot/
always failed because the artifact zip filename doesn't contain the JDK major version as usualy.

**Comment by douph1** [comment]
After merging the job must evolv to check %ERRORLEVEL% and fail fast

```
set WIX="C:\PROGRA~2\WIXTOO~1.14\"
set PRODUCT_CATEGORY=jdk
cd wix\SourceDir
call powershell.exe ./CreateSourceFolder.AdoptOpenJDK.ps1
cd %WORKSPACE%\wix
call Build.OpenJDK_generic.cmd
```

```
set WIX="C:\PROGRA~2\WIXTOO~1.14\"
set PRODUCT_CATEGORY=jdk
cd wix\SourceDir
call powershell.exe ./CreateSourceFolder.AdoptOpenJDK.ps1
IF ERRORLEVEL 1 (
 ECHO unzip failedEXIT /b 2                                                                                                                                                                )
--



cd %WORKSPACE%\wix
call Build.OpenJDK_generic.cmd
```

**Comment by aahlenst** [comment]
@douph1 I updated `create_installer_windows` as described. There's a second step for JRE that looks significantly different, so I don't feel comfortable changing it on my own:

```
set WIX="C:\PROGRA~2\WIXTOO~1.14\"
set PRODUCT_CATEGORY=jre
cd %WORKSPACE%\wix

call Build.OpenJDK_generic.cmd
if %ERRORLEVEL% neq 0 goto BuildError

:BuildError
@rem Looks like I didn't have a JRE.
exit /b 0
```

Do you have access to Jenkins? standalone_create_installer_windows deserves an update, too.

**Comment by douph1** [comment]
some build in failure :
exemple 
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/4013/console
```
J:\jenkins\workspace\build-scripts\release\create_installer_windows\wix\SourceDir>call powershell.exe ./CreateSourceFolder.AdoptOpenJDK.ps1 
filename : icedtea-web-1.8.3.win.bin.zip don't match regex ^OpenJDK\d+

J:\jenkins\workspace\build-scripts\release\create_installer_windows\wix\SourceDir>IF ERRORLEVEL 1 (
ECHO unzip failed  
 EXIT /b 2 
) 
```

I have fixed it by removing icedtea*.zip after unpacking in installer job
`rm icedtea-web-*.win.bin.zip `

fixed : https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/4016/console

**Comment by douph1** [comment]
> @douph1 I updated `create_installer_windows` as described. There's a second step for JRE that looks significantly different, so I don't feel comfortable changing it on my own:
Don't need to be changed as it dont exec CreateSourceFolder.AdoptOpenJDK.ps1
> 
> ```
> set WIX="C:\PROGRA~2\WIXTOO~1.14\"
> set PRODUCT_CATEGORY=jre
> cd %WORKSPACE%\wix
> 
> call Build.OpenJDK_generic.cmd
> if %ERRORLEVEL% neq 0 goto BuildError
> 
> :BuildError
> @rem Looks like I didn't have a JRE.
> exit /b 0
> ```
> 
> Do you have access to Jenkins? standalone_create_installer_windows deserves an update, too.

Yes,
standalone_create_installer_windows, I will take a look

**Comment by douph1** [comment]
test_installer_windows and standalone_create_installer_windows and create_installer_windows all green
