### ISSUE TITLE
Windows installer job don't found jdk folder for JDK-Next release which is not numbered in artifact name

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/openjdk-installer#211]
last failure : https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/4110/console

Because we actually need to build two installer at a time ( one job run ) for jdk+jre ( or for testing purpose) 
CreateSourceFolder.AdoptOpenJDK.ps1 loop through all zip(artifacts) files found.
This is good for testing.
It extract all and then create installers for all jdk version in one launch
but this is not the best behavior for jenkins.

We must rely on Jenkins jobs parameters to extract only artifact copied from downstream job
and create installer only for parameters passed wich must be less error prone than parsing archive file name.

Ideally it can bee cleanly done if
1) all the required params are defined in job parameters by upstream job
2) downstream job only create/copy one artifact at a time.

This don't seems the case as one job run can build two installer : `Copied 2 artifacts from`
with each one is own folder
`Source dir used : .\SourceDir\OpenJDK8\hotspot\x86-32\jdk8u262-b03`
`Source dir used : .\SourceDir\OpenJDK8\hotspot\x86-32\jdk8u262-b03-jre`

Hopefully both files unzip in different folder ...

but as we create installer for two msi at one time
1) we need to extract zip on different folder on determined the path for each
2) we can't rely on job parameter to know if we want to build installer for a JRE or a JDK or both
3) it lead to possibly ignoring error as this step in the installer job :
`set PRODUCT_CATEGORY=jre
cd %WORKSPACE%\wix

call Build.OpenJDK_generic.cmd
if %ERRORLEVEL% neq 0 goto BuildError

:BuildError
@rem Looks like I didn't have a JRE.
exit /b 0`

here .. after JDK installer was create we try to build JRE installer and if we failed, we just ignoring the failure ..

I hope I have not missed some bad behaviour of our actual installer build step.

Can the upstream job trigger two installer job to run with each one only one artifact (JRE if revelent) and one other job run with other artifact and JDK parameter ?

**Comment by karianna** [comment]
@M-Davies - Does this resonate?

**Comment by M-Davies** [comment]
I'm hoping https://github.com/AdoptOpenJDK/openjdk-build/pull/1764/ will resolve this if it gets accepted. If not, I can look into other ways of filtering which jobs get passed down to the installer

**Comment by douph1** [comment]
resolved/fixed with #216 #217 #218 #219
and https://github.com/AdoptOpenJDK/openjdk-build/pull/1790 and https://github.com/AdoptOpenJDK/openjdk-build/pull/1823
