### ISSUE TITLE
Add support to the installer for creating packages on RISCV

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-installer#213]
`uname` output is as follows:
`Linux stage4.fedoraproject.org 4.19.0-rc8 #1 SMP Wed Oct 17 15:11:25 UTC 2018 riscv64 riscv64 riscv64 GNU/Linux`
I believe various parts of the code will be updated to handle the RISC-V architecture, starting with [Architecture.java](https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/linux/buildSrc/src/main/java/net/adoptopenjdk/installer/Architecture.java)

The failures are in the installer jobs created during https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-riscv-openj9/

```
> Task :buildSrc:validatePlugins
> Task :buildSrc:check
> Task :buildSrc:build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jenkins/workspace/build-scripts/release/create_installer_linux/linux/build.gradle' line: 73

* What went wrong:
A problem occurred evaluating root project 'linux'.
> No enum constant net.adoptopenjdk.installer.Architecture.RISCV

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by aahlenst** [comment]
@sxa Maybe you know that stuff from the top of your head: Which distributions have official RISCV ports? Where can I buy they hardware for development?

**Comment by sxa** [comment]
Fedora and Debian certainly do. I mostly use a qemu VM for script development. You can log into one of ours if it helps for anything, but we don't build the installers on each architecture right?

**Comment by sxa** [comment]
If you really want to buy your own, https://www.sifive.com is one source of boards.

**Comment by aahlenst** [comment]
We do all builds on AMD64. I still have to validate that everything's working as supposed and for that I need the target platform. I'll brush up my QEMU skills and see if it's sufficiently fast.

**Comment by sxa** [comment]
Should be fine for testing installations. We haven't got a Debian qemu system but we have Fedora working :-)
