### ISSUE TITLE
Windows installer build failure fail to guess folder name

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/openjdk-installer#216]
As discussed in https://github.com/AdoptOpenJDK/openjdk-installer/pull/212
The installer must guess the jdk folder name based on the build param

Error : https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/4310/console
```
First .\SourceDir\OpenJDK15\hotspot\x64\jdk-15.0.0 not exists
Second .\SourceDir\OpenJDK15\hotspot\x64\jdk-15+25 not exists
Third .\SourceDir\OpenJDK15\hotspot\x64\jdk-15.0.0+25 not exists
OpenJDK-Latest unnumbered .\SourceDir\OpenJDK-Latest\hotspot\x64\jdk-15.0.0+25 does not exist
SOURCE Dir not found / failed
```

It seems the folder name inside the zip archive is like JEP322 .. but not exactly
Here some sample of JEP322_NAME as I understand it and the created Adopt folder name.

If the installer guess the folder like ADOPT_NAME do you think this sample list will match what the upstream job put into the zip file ?

**Test JDK versionning**
Basic      =11.0.0.12
JEP322_NAME=11+12-LTS
ADOPT_NAME =jdk-11+12

Basic      =11.0.14.18
JEP322_NAME=11.0.14+18-LTS
ADOPT_NAME =jdk-11.0.14+18

Basic      =11.1.0.28
JEP322_NAME=11.1+28-LTS
ADOPT_NAME =jdk-11.1+28

Basic      =14.0.0.35
JEP322_NAME=14+35
ADOPT_NAME =jdk-14+35

Basic      =14.0.1.36
JEP322_NAME=14.0.1+36
ADOPT_NAME =jdk-14.0.1+36

Basic      =14.0.0.35
JEP322_NAME=14+35
ADOPT_NAME =jdk-14+35

**Test JRE versionning**
Basic      =11.0.0.12
JEP322_NAME=11+12-LTS
ADOPT_NAME =jdk-11+12-jre

Basic      =11.0.14.18
JEP322_NAME=11.0.14+18-LTS
ADOPT_NAME =jdk-11.0.14+18-jre

Basic      =11.1.0.28
JEP322_NAME=11.1+28-LTS
ADOPT_NAME =jdk-11.1+28-jre

Basic      =14.0.0.35
JEP322_NAME=14+35
ADOPT_NAME =jdk-14+35-jre

Basic      =14.0.1.36
JEP322_NAME=14.0.1+36
ADOPT_NAME =jdk-14.0.1+36-jre

Basic      =14.0.0.35
JEP322_NAME=14+35
ADOPT_NAME =jdk-14+35-jre

**Comment by karianna** [comment]
@gdams and @johnoliver - might be worth a sanity check on the version naming here. It looks good to me...
