### ISSUE TITLE
Include IcedTea-Web in AdoptOpenJDK installer

### ISSUE THREAD

**Issue by don-vip** [AdoptOpenJDK/openjdk-installer#22]
It would be great if the AdoptOpenJDK install also include [IcedTea-Web](https://icedtea.classpath.org/wiki/IcedTea-Web) natively, to ease the transition from Oracle JRE for Java WebStart applications.

IcedTea-Web is developed by RedHat and works on Linux, Windows and possibly also on macOS.

**Comment by karianna** [comment]
Need to have a long hard think about supporting this out of the box.  WebStart has been deprecated/removed due to significant security concerns but we do of course sympathize with those who have no other choice.

Perhaps an alternative bundle can be produced.

**Comment by smlambert** [comment]
I am definitely interested in this one :)  - we have played around with this locally, and have fielded a good number of queries about it.

**Comment by don-vip** [comment]
Do you have concrete information about those security concerns? Every time I tried to ask details to Oracle about that, they never answered. As WebStart requires code signing, I don't see it as a less secure technology than distributing standalone unsigned Java applications on the Internet.

**Comment by charliegracie** [comment]
I was just about to open an Issue for the exact same thing! I think one of the great aspects AdoptOpenJDK can bring to the table is improving the out of the box developer experience. I would be willing to help add this functionality. IcedTea-Web binaries can easily be downloaded for the Windows platform (here)[http://icedtea.wildebeest.org/download/icedtea-web-binaries/]. It looks like it would be a very simple change to add this functionality to the Windows build as an experiment. I think in the longer term it should be fairly easy to build it for all platforms as part of the build process if that makes sense.

**Comment by charliegracie** [comment]
@karianna I am not that familiar with the Windows installer and how to use it. I am wondering if the AdoptOpenJDK Windows installer could provide an option that user would select at install time to allow it to install the IcedTea-Web as part of the install.  This would mean it would not be installed or packaged by default but that the user could choose to install it at the same time they are installing the JDK and into a location that would allow it to work seamlessly with the JDK.  Thoughts?

**Comment by gdams** [comment]
yeah I'd say a tick box would be the obvious way to handle this! thoughts @alexhass ?

**Comment by alexhass** [comment]
Sure, can be an optional feature.

**Comment by charliegracie** [comment]
What is the current status of the Windows installer? Is it ok if I go ahead and try to prototype the optional install of IcedTea-Web?

Does AdoptOpenJDK currently create Windows installer packages available for download? Is this something that is expected to be offered? Is there work I can do to help with this?

**Comment by charliegracie** [comment]
Thanks! @karianna is there a timeframe for when you think the MSI builds will be integrated into the pipelines?

**Comment by gdams** [comment]
we are trying to work with @alexhass to get these implemented ASAP

**Comment by Viggy1** [comment]
Any status on this? I also would love to see an installer for Icedtea-web.

**Comment by karianna** [comment]
This will get some priority in Q1 next year (likely January)

**Comment by brenwhyte** [comment]
Any update on this?

**Comment by karianna** [comment]
First installer meeting is happening this week, we're looking to get the Windows MSI installer up and running.  After that, we can figure out how to bundle Iced-Tea.  You can join our team at adoptopenjdk.net/slack.html

**Comment by don-vip** [comment]
If [OpenWebStart](https://dev.karakun.com/webstart/) becomes a reality, it might be an improvement of IcedTea-Web, thus a better choice. Quoting Karakun: 

> Currently we are looking for funding. Once funding is secured, we will start development. Beta tests might be availabe in Q2 2019.

**Comment by Artoria2e5** [comment]
IcedTea folks have a Windows MSI/ZIP build at http://icedtea.wildebeest.org/download/icedtea-web-binaries/1.7.2/windows/. You can start playing with it. It lacks an option to associate .jnlp files by default, which is a mild annoyance.

In the unlikely case it becomes unhappy with newer versions of Java (removal of `sun.applet.AppletImageRef`), copying stuff from OpenJDK 9 seems to work (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912549). I heard that the use of that removed thing is removed in 1.7.2.

**Comment by douph1** [comment]
> What is the current status of the Windows installer?

In production

>Is it ok if I go ahead and try to prototype the optional install of IcedTea-Web?

Yes sure go on

> Does AdoptOpenJDK currently create Windows installer packages available for download?

Yes now it's reality with many bugs closed for next released

> Is this something that is expected to be offered?

Msi are available for download 

>Is there work I can do to help with this?

Yes go on please

**Comment by douph1** [comment]
WIP https://github.com/AdoptOpenJDK/openjdk-installer/pull/87

**Comment by mfriedenhagen** [comment]
Just last week I extracted `netx.jar` from Debian's `icedtea-netx_1.7.2-2_all.deb` and started a jnlp file like `java -cp netx.jar net.sourceforge.jnlp.runtime.Boot -Xnofork -jnlp XXX.jnlp`, following instructions found at https://apple.stackexchange.com/questions/342943/in-macos-how-to-run-a-jnlp-file-with-openjdk-8. Worked like a charme.

**Comment by gdams** [comment]
closing, ITW 1.8.1 has landed, installers will be bundled with it in the next release and nightlies are already available for testing.

**Comment by mauromol** [comment]
This is great news! :-)

**Comment by don-vip** [comment]
Thanks a lot!

**Comment by wanderleihuttel** [comment]
Hello
I'm installed JRE (OpenJDK8U-jre_x64_windows_hotspot_8u212b03.msi) and (1.8 itw-installer.msi) but it doesn't work like Oracle JRE. 
The applications that has executable files, it looks works fine, but I'm talking about (.jnlp and .jar files).
Is not possible to only do a double click to open.
There is some tip to make work like Oracle JRE?

**Comment by maverick74** [comment]
@wanderleihuttel is this related to #32?

**Comment by wanderleihuttel** [comment]
@maverick74. 
Yes, is related!

**Comment by wanderleihuttel** [comment]
@maverick74 , just for knowing! 
I'm tested ojdkbuild (https://github.com/ojdkbuild/ojdkbuild) and this project is possible to install ITW together.
Could be something like that.

**Comment by karianna** [comment]
@douph1 Is this like an installer issue or an ITW issue?  I'd like to open a bug in the correct repo.

**Comment by douph1** [comment]
1.8 itw-installer.msi is from https://github.com/AdoptOpenJDK/icedtea-web

**Comment by douph1** [comment]
@wanderleihuttel by default installer install reg key per machine ( for all users )
but if you have registered something per user , user config is used first

**Comment by douph1** [comment]
IcedTea-Web is/will only be available since build 8u2012b04 ( already out for openj9 ) and pending for hotspot
