### ISSUE TITLE
Digital Signature Certificate runs out 08/09/2020. Will you update it for 8_262? 

### ISSUE THREAD

**Issue by julianrichmond** [AdoptOpenJDK/openjdk-installer#222]
We have systems that check the .exe certificate and make sure its valid.

Your current certificate will run out soon.

Thanks

**Comment by aahlenst** [comment]
@gdams In my opinion, it makes sense to update the certificate before the July CPU in order not to have to rebuild it later on. I assume this is something you have to do (happy to help if I can). Do we have a system in place that reminds us about such things?

**Comment by gdams** [comment]
@karianna following on from our conversation earlier...

**Comment by douph1** [comment]
As far as I know if we sign with timestamp server before expiry the signature will always be valid even after the expiry.

**Comment by julianrichmond** [comment]
I see you have produced 8_262 without updating the digital signature certificate.
The release date for 8_272 is after it has expired so thats a bit late.
Have you any plans for patching 8_262?

Thanks

**Comment by aahlenst** [comment]
Internal testing indicated that packages built with the old certificate install just fine if we forward the clock to 2021.

**Comment by gdams** [comment]
We timestamp the binaries so we should be okay

**Comment by julianrichmond** [comment]
I believe if you are using a tool such as Microsofts AppLocker (and maybe bitlocker) it can be configured to stop executables from running that have certificates which have expired. 
We have had issues with our own executables when this has happened.

**Comment by aahlenst** [comment]
Reading https://docs.microsoft.com/en-us/windows/win32/seccrypto/time-stamping-authenticode-signatures, we're doing everything as devised by Microsoft. Before rushing to action and having to do a lot of work, I like to see steps to verify the behavior you're describing. Furthermore, without those, it is impossible to verify whether we've taken the right steps.

**Comment by julianrichmond** [comment]
I have had feedback from one of our technical people and yes, you are correct.
We had an issue with our executable because the certificate we used was not timestamped so when it ran out it was blocked by AppLocker.
Your certificate has been timestamped so even when it runs out the timestamp element still makes it valid.

Sorry for my lack of understanding on these matters.

**Comment by aahlenst** [comment]
Great! It never hurts to challenge assumptions. I learnt more about Authenticode in the last days than I ever wanted :grin:
