### ISSUE TITLE
Variant number is not increased when new rpms of the same build is published

### ISSUE THREAD

**Issue by farmdawgnation** [AdoptOpenJDK/openjdk-installer#226]
**Platform:** CentOS 7 (but probably affects others)

**Architecture:** x86_64 (but probably affects others)

When changes are released to the rpm packages release branch (not nightly) without changing the version of the JRE or JDK, the variant number on the rpm package should be increased so that the fact that there have been changes is evident _and_ each rpm in the release repo is an immutable artifact.

**Comment by karianna** [comment]
As @aahlenst this has been built in
