### ISSUE TITLE
Cannot upgrade from adoptopenjdk-8-openj9-8u252_b09.openj9_0.20.0-1.x86_64 to adoptopenjdk-8-openj9-8u262_b10.openj9_0.21.0-1.x86_64

### ISSUE THREAD

**Issue by lcollins** [AdoptOpenJDK/openjdk-installer#236]
Please raise an issue at https://github.com/AdoptOpenJDK/openjdk-installer or https://github.com/AdoptOpenJDK/homebrew-openjdk if it's an issue with our brew casks

```
Resolving Dependencies
--> Running transaction check
---> Package adoptopenjdk-8-openj9.x86_64 0:8u252_b09.openj9_0.20.0-1 will be updated
---> Package adoptopenjdk-8-openj9.x86_64 0:8u262_b10.openj9_0.21.0-1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================================================================================================================================================
 Package                                                               Arch                                                   Version                                                                      Repository                                                    Size
==============================================================================================================================================================================================================================================================================
Updating:
 adoptopenjdk-8-openj9                                                 x86_64                                                 8u262_b10.openj9_0.21.0-1                                                    AdoptOpenJDK                                                 109 M

Transaction Summary
==============================================================================================================================================================================================================================================================================
Upgrade  1 Package

Total size: 109 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test


Transaction check error:
  file /usr/lib/jvm/adoptopenjdk-8-openj9/man/ja from install of adoptopenjdk-8-openj9-8u262_b10.openj9_0.21.0-1.x86_64 conflicts with file from package adoptopenjdk-8-openj9-8u252_b09.openj9_0.20.0-1.x86_64

Error Summary
-------------
```

**Comment by aahlenst** [comment]
A Gradle bug leads to a RPM bug, yay! To quote https://rpm.org/user_doc/faq.html:

> How can I replace a directory with a symlink or vice-versa?
> 
> You dont. If you are desperate, it can be achieved with a %pretrans scriptlet written with the embedded Lua interpreter, but this is fragile at best. The Fedora project [has examples and further guidance](https://docs.fedoraproject.org/en-US/packaging-guidelines/Directory_Replacement/) you might be helpful.

So let's see if I can get a scriptlet into FPM.

**Comment by aahlenst** [comment]
Scriptlets must be written in lua but FPM does not allow that, see https://github.com/jordansissel/fpm/issues/1666. There's no fast way around that.

The best workaround I can think of:

``` 
rm -rf /usr/lib/jvm/adoptopenjdk-8-openj9/man/ja
yum upgrade
```

**Comment by aahlenst** [comment]
We're in an awkward place:

* People that already have the newest versions (8u262, 11.0.8) have the symlink, people with the old versions have the directory. So even if we go back to the directory, we break the people with the symlink.
* Replacing fpm right now is not really an option (lot of work, risk of other breakages is high). 
* Patching fpm is not really an option (would require fork, testing facilities do not seem to be in good shape).
* Pretrans is only possible with a shell script, would break people in Kickstart scenarios.
* Creating the symlinks in the post install script does not work because the removal of the old package during an update would remove the symlink.

So, the best option (read: lowest impact) I've come up with: Remove the offending directory/symlink `man/ja` entirely from the package. This works for everyone, the Japanese man pages are still there (but in a different directory) and aren't included in 14 and newer anyway. We can still bring them back in the future.

There's an open PR that fixes the problem. As soon as it's merged, we'll publish new packages.

**Comment by aahlenst** [comment]
The new packages for 8u262 are in. 11.0.8 is currently being uploaded. Might need `yum update --refresh` to get the `-2` package.

**Comment by lcollins** [comment]
I can confirm this has resolved my issue. Thank you for the quick turnaround 

`[lcollins@uk-lon01-vps001 ~]$ sudo yum update
Loaded plugins: changelog, elrepo, fastestmirror, product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

Loading mirror speeds from cached hostfile
 * base: mirror.sov.uk.goscomb.net
 * centos-sclo-rh: mirror.sov.uk.goscomb.net
 * centos-sclo-sclo: mirror.sov.uk.goscomb.net
 * elrepo: ftp.nluug.nl
 * extras: uk.mirror.nsec.pt
 * remi: mirror.netweaver.uk
 * remi-php72: mirror.netweaver.uk
 * remi-safe: mirror.netweaver.uk
 * rpmforge: mirrors.ircam.fr
 * updates: mirror.as29550.net
AdoptOpenJDK                                                                                                                                                                   | 1.4 kB  00:00:00
CodeIT                                                                                                                                                                         | 2.9 kB  00:00:00
CodeITmainline                                                                                                                                                                 | 2.9 kB  00:00:00
ansible                                                                                                                                                                        | 2.9 kB  00:00:00
as-repo-centos7                                                                                                                                                                | 2.9 kB  00:00:00
base                                                                                                                                                                           | 3.6 kB  00:00:00
centos-sclo-rh                                                                                                                                                                 | 3.0 kB  00:00:00
centos-sclo-sclo                                                                                                                                                               | 3.0 kB  00:00:00
copr:copr.fedorainfracloud.org:jdoss:wireguard                                                                                                                                 | 3.3 kB  00:00:00
cr                                                                                                                                                                             | 2.9 kB  00:00:00
datadog                                                                                                                                                                        | 2.5 kB  00:00:00
digitalocean-agent                                                                                                                                                             | 3.3 kB  00:00:00
docker-ce-stable                                                                                                                                                               | 3.5 kB  00:00:00
elrepo                                                                                                                                                                         | 2.9 kB  00:00:00
epel                                                                                                                                                                           | 4.7 kB  00:00:00
extras                                                                                                                                                                         | 2.9 kB  00:00:00
jenkins                                                                                                                                                                        | 2.9 kB  00:00:00
lynis                                                                                                                                                                          | 2.5 kB  00:00:00
mysql-connectors-community                                                                                                                                                     | 2.5 kB  00:00:00
mysql-tools-community                                                                                                                                                          | 2.5 kB  00:00:00
mysql57-community                                                                                                                                                              | 2.5 kB  00:00:00
nodesource                                                                                                                                                                     | 2.5 kB  00:00:00
remi                                                                                                                                                                           | 3.0 kB  00:00:00
remi-php72                                                                                                                                                                     | 3.0 kB  00:00:00
remi-safe                                                                                                                                                                      | 3.0 kB  00:00:00
remi-test-debuginfo                                                                                                                                                            | 3.0 kB  00:00:00
rpmforge                                                                                                                                                                       | 1.9 kB  00:00:00
rundeck-release-bintray                                                                                                                                                        | 1.3 kB  00:00:00
updates                                                                                                                                                                        | 2.9 kB  00:00:00
yarn                                                                                                                                                                           | 2.9 kB  00:00:00
(1/5): epel/x86_64/updateinfo                                                                                                                                                  | 1.0 MB  00:00:00
(2/5): remi-safe/primary_db                                                                                                                                                    | 1.7 MB  00:00:00
(3/5): remi/primary_db                                                                                                                                                         | 2.7 MB  00:00:00
(4/5): epel/x86_64/primary_db                                                                                                                                                  | 6.9 MB  00:00:00
(5/5): AdoptOpenJDK/7/x86_64/primary                                                                                                                                           |  34 kB  00:00:01
AdoptOpenJDK                                                                                                                                                                                  138/138
[elrepo]: 46 kmod packages excluded due to dependency errors
Resolving Dependencies
--> Running transaction check
---> Package ImageMagick.x86_64 0:6.9.11.23-1.el7.remi will be updated
---> Package ImageMagick.x86_64 0:6.9.11.24-1.el7.remi will be an update
---> Package ImageMagick-libs.x86_64 0:6.9.11.23-1.el7.remi will be updated
---> Package ImageMagick-libs.x86_64 0:6.9.11.24-1.el7.remi will be an update
---> Package adoptopenjdk-8-openj9.x86_64 0:8u252_b09.openj9_0.20.0-1 will be updated
---> Package adoptopenjdk-8-openj9.x86_64 0:8u262_b10.openj9_0.21.0-2 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

======================================================================================================================================================================================================
 Package                                             Arch                                 Version                                                    Repository                                  Size
======================================================================================================================================================================================================
Updating:
 ImageMagick                                         x86_64                               6.9.11.24-1.el7.remi                                       remi                                        90 k
 ImageMagick-libs                                    x86_64                               6.9.11.24-1.el7.remi                                       remi                                       2.4 M
 adoptopenjdk-8-openj9                               x86_64                               8u262_b10.openj9_0.21.0-2                                  AdoptOpenJDK                               109 M

Transaction Summary
======================================================================================================================================================================================================
Upgrade  3 Packages

Total download size: 112 M
Is this ok [y/d/N]: y
Downloading packages:
No Presto metadata available for remi
No Presto metadata available for AdoptOpenJDK
(1/3): ImageMagick-6.9.11.24-1.el7.remi.x86_64.rpm                                                                                                                             |  90 kB  00:00:00
(2/3): ImageMagick-libs-6.9.11.24-1.el7.remi.x86_64.rpm                                                                                                                        | 2.4 MB  00:00:00
(3/3): adoptopenjdk-8-openj9-8u262-b10.openj9-0.21.0-2.x86_64.rpm                                                                                                              | 109 MB  00:00:30
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                 3.7 MB/s | 112 MB  00:00:30
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : ImageMagick-libs-6.9.11.24-1.el7.remi.x86_64                                                                                                                                       1/6
  Updating   : ImageMagick-6.9.11.24-1.el7.remi.x86_64                                                                                                                                            2/6
  Updating   : adoptopenjdk-8-openj9-8u262_b10.openj9_0.21.0-2.x86_64                                                                                                                             3/6
  Cleanup    : ImageMagick-6.9.11.23-1.el7.remi.x86_64                                                                                                                                            4/6
  Cleanup    : ImageMagick-libs-6.9.11.23-1.el7.remi.x86_64                                                                                                                                       5/6
  Cleanup    : adoptopenjdk-8-openj9-8u252_b09.openj9_0.20.0-1.x86_64                                                                                                                             6/6
  Verifying  : ImageMagick-6.9.11.24-1.el7.remi.x86_64                                                                                                                                            1/6
  Verifying  : adoptopenjdk-8-openj9-8u262_b10.openj9_0.21.0-2.x86_64                                                                                                                             2/6
  Verifying  : ImageMagick-libs-6.9.11.24-1.el7.remi.x86_64                                                                                                                                       3/6
  Verifying  : adoptopenjdk-8-openj9-8u252_b09.openj9_0.20.0-1.x86_64                                                                                                                             4/6
  Verifying  : ImageMagick-libs-6.9.11.23-1.el7.remi.x86_64                                                                                                                                       5/6
  Verifying  : ImageMagick-6.9.11.23-1.el7.remi.x86_64                                                                                                                                            6/6

Updated:
  ImageMagick.x86_64 0:6.9.11.24-1.el7.remi                  ImageMagick-libs.x86_64 0:6.9.11.24-1.el7.remi                  adoptopenjdk-8-openj9.x86_64 0:8u262_b10.openj9_0.21.0-2

Complete!
[lcollins@uk-lon01-vps001 ~]$`
