### ISSUE TITLE
`MSIINSTALLPERUSER` and `INSTALLDIR` not working for MSI

### ISSUE THREAD

**Issue by Eskibear** [AdoptOpenJDK/openjdk-installer#246]
Originally repoted in https://github.com/microsoft/vscode-java-installer/issues/53#issuecomment-683832774

Run the Adopt MSI with below options:
* MSIINSTALLPERUSER=1
* INSTALLDIR=C:\Users\admin\AppData\Local\Programs\AdoptOpenJDK

But the JDK was wrongly installed into "C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\"

```
...
MSI (s) (68:8C) [00:05:11:832]: Command Line: MSIINSTALLPERUSER=1 INSTALLDIR=C:\Users\admin\AppData\Local\Programs\AdoptOpenJDK ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith REBOOTPROMPT=S CURRENTDIRECTORY=C:\Users\admin\AppData\Local\Temp\1fIPpovDGCeTmgxsgBFJybvqTBE CLIENTUILEVEL=2 CLIENTPROCESSID=2070612
...
MSI (s) (68:8C) [00:05:30:468]: Doing action: PerMachineInstall
MSI (s) (68:8C) [00:05:30:468]: Note: 1: 2205 2:  3: ActionText
Action ended 00:05:30: FileCost. Return value 1.
MSI (s) (68:8C) [00:05:30:469]: PROPERTY CHANGE: Adding TARGETDIR property. Its value is 'C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\'.
Action start 00:05:30: PerMachineInstall.
MSI (s) (68:8C) [00:05:30:469]: Skipping action: PerUserInstall (condition is false)
...

```

full logs: 
[AdoptOpenJDK-MSI.log](https://github.com/AdoptOpenJDK/openjdk-installer/files/5160438/AdoptOpenJDK-MSI.log)

**Comment by douph1** [comment]
Does the same apply with non admin user ?

**Comment by douph1** [comment]
MSI (s) (68:8C) [00:05:30:469]: Skipping action: PerUserInstall (condition is false)

**Comment by douph1** [comment]
I can't say more, the install path is ignored because the installer switch to PerMachineInstall

**Comment by aahlenst** [comment]
This is the critical line:

```
MSI (s) (68:8C) [00:05:11:832]: Determined that existing product (either this product or the product being upgraded with a patch) is installed per-machine.
```

It's like with https://github.com/AdoptOpenJDK/openjdk-installer/issues/196. MSIs aren't a great fit for multiple installations.

**Comment by Eskibear** [comment]
@aahlenst About the critical line you mentioned, is it saying the user has installed AdoptOpenJDK before, and it is a) exact the same version 11.0.8, b) per machine ?

From the `PATH` I can say the user did have Oracle JDK installed, but not sure about AdoptOpenJDK (because AFAIK Adopt will modify PATH). 
```
PATH: C:\Program Files (x86)\Google\Chrome\Application;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python\Python3.8.5\Scripts;C:\Python\Python3.8.5\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\MinGW\bin;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\admin\AppData\Roaming\npm;C:\Program Files\Docker Toolbox;C:\Program Files\Docker Toolbox;C:\Program Files\Docker Toolbox;D:\soft\IntelliJ IDEA Community Edition 2020.2\bin;;C:\Program Files\Redis;
``` 

I think @Rupeshiya would be willing to help if you need more details to figure out why it happened.

**Comment by douph1** [comment]
>a) exact the same version 11.0.8
not the exact the same see below

see https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/wix/Build.OpenJDK_generic.cmd
L172-184
        SET SOURCE_TEXT_GUID=!PRODUCT_CATEGORY!-!PRODUCT_MAJOR_VERSION!-!PLATFORM!-!PACKAGE_TYPE!

=>
PRODUCT_CATEGORY=JRE vs JDK
PRODUCT_MAJOR_VERSION=11 vs others
PLATFORM=x86 vs x64
PACKAGE_TYPE=hotspot vs openj9

 b) per machine ?
yes

**Comment by douph1** [comment]
@Eskibear any other question ? can we close it ?

**Comment by Eskibear** [comment]
Thanks for the clarification.
