### ISSUE TITLE
PPA Personal Package Archives für Linux

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/openjdk-installer#249]
Does Adopt already provide PPA Personal Package Archives für Linux? Does it make sense to offer them?

**Comment by aahlenst** [comment]
Debian packages and RPM: https://adoptopenjdk.net/installation.html#linux-pkg

Alpine APK is on the list. The challenges for creating a PPA are listed in  https://github.com/AdoptOpenJDK/openjdk-installer/issues/201. Basically, we need help from Canonical and they'd have to allow binary uploads.
