### ISSUE TITLE
Problem with MergeList /var/lib/apt/lists/adoptopenjdk.jfrog.io ...

### ISSUE THREAD

**Issue by flobernd** [AdoptOpenJDK/openjdk-installer#254]
Hi there,

I'm getting 

```
Problem with MergeList /var/lib/apt/lists/adoptopenjdk.jfrog.io_adoptopenjdk_deb_dists_buster_main_binary-amd64_Packages
```

when trying to `apt update`.

It seems like your repository was causing this issue in the past already. Could you please have another look?

Best regards

**Comment by aahlenst** [comment]
Tracking in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1647.
