### ISSUE TITLE
Produce RPM binaries

### ISSUE THREAD

**Issue by keirlawson** [AdoptOpenJDK/openjdk-installer#26]
It would be great is AdoptOpenJDK could also ship RPM binaries just as Oracle currently do for their JDK.  Redhat-based distributions are very common deployment platforms and this would ease the transition for people used to getting their JDK RPMs directly form Oracle.

**Comment by flybd5** [comment]
A set of commands to convert the tar.gz's for X64 into Debian packages has been cobbled up here: https://github.com/AdoptOpenJDK/openjdk-installer/issues/25

**Comment by zhangm13** [comment]
Hi, 

I'm currently working on an openliberty rpm and deb package and would like to incorporate the AdoptOpenJDK rpm/deb. I was wondering if you guys would be working on it anytime soon.

**Comment by flybd5** [comment]
Use fpm to produce your deb. Works for me.

**Comment by kristi** [comment]
Are there rpm installers now? The Migration guide suggests that there are beta rpms somewhere

**Comment by karianna** [comment]
> Are there rpm installers now? The Migration guide suggests that there are beta rpms somewhere

Not yet no, we have MSI and Maca OS X installers pretty much sorted, more coming soon.

**Comment by kristi** [comment]
I got impatient and I built myself an adoptopenjdk8 rpm here: https://github.com/kristi/adoptopenjdk-rpm/releases  Maybe it'll be useful to others too

**Comment by gdams** [comment]
@kristi would you be happy to contribute your work to the project? We could then look at building and shipping them from our website

**Comment by kristi** [comment]
Yeah, I'd be happy to contribute

**Comment by gdams** [comment]
@kristi can we setup a call to discuss this further?

**Comment by dennisl** [comment]
I think that the solution for https://github.com/AdoptOpenJDK/openjdk-installer/issues/25 have solved this. See the docs at https://github.com/AdoptOpenJDK/openjdk-installer/tree/master/linux for more info.

**Comment by gdams** [comment]
Closing as this is now complete! check out https://medium.com/adoptopenjdk/adoptopenjdk-rpm-and-deb-files-7003ba38144e for more info!
