### ISSUE TITLE
Provide MSI installer

### ISSUE THREAD

**Issue by alexhass** [AdoptOpenJDK/openjdk-installer#27]
We are looking to migrate away all products from Oracle Java to OpenJDK.

To be able to deploy OpenJDK and OpenJRE in enterprise we need MSI installers. Currently I only see a ZIP file as download.

Can you create an MSI setup, please?

**Comment by karianna** [comment]
@alexhass Are you able to jump onto our Slack at https://www.adoptopenjdk.net/slack.html?  Would be great to chat about the MSI installer there.

**Comment by alexhass** [comment]
I do not have a slack account and I do not like to give my personal data to another unknown US company. No idea what they are doing with my data.

**Comment by maverick74** [comment]
Would be nice to se #4 included here as well.

What's the state of this issue? Any progress?

**Comment by karianna** [comment]
We'll be looking to integrate this into the pipelines over the coming weeks.

**Comment by alexhass** [comment]
Have you finished the integration? Oracle Java 8 support ends very soon and we should have a solution asap - best with JavaFX included or the releases are not really useful for many users. Otherwise people would be locked to insecure Java 8 version from Oracle.

**Comment by hypercube33** [comment]
I too would like an update on this, technically Java 8 was supposed to end of life this month but looks like it got bumped out a little bit. A lot of people would potentially benefit from the MSI JRE installers at the least. Thanks!

**Comment by gdams** [comment]
@alexhass can we jump on a call together to go through your work and get this implemented into our pipelines?

**Comment by alexhass** [comment]
Yes.

**Comment by gdams** [comment]
@alexhass how does Monday 21st Jan at 2PM GMT work for you?

**Comment by alexhass** [comment]
send you an email.

**Comment by gdams** [comment]
@alexhass https://ibm.webex.com/join/george.adams

**Comment by milltertime** [comment]
Thank you very much for your effort and gdamns.

I have experience with packaging and deployment via sccm and would be happy to help here I can!

**Comment by gdams** [comment]
closing as the final bits can be handled in https://github.com/AdoptOpenJDK/openjdk-installer/issues/50.

@lootkips if you would like to get involved in the efforts drop me a message on our slack channel. (aojdk.net/slack)

**Comment by treado** [comment]
Hi guys, does anyone know if AdoptOpenJDK will be providing installers for OpenJDK 11, like they do for OpenJDK 8?

**Comment by karianna** [comment]
> Hi guys, does anyone know if AdoptOpenJDK will be providing installers for OpenJDK 11, like they do for OpenJDK 8?

We're working on the installers right now - hopefully, we'll see these rolling out next week.

**Comment by Phillipus** [comment]
> We're working on the installers right now - hopefully, we'll see these rolling out next week.

That would be very helpful, thanks!

**Comment by baramundi-rklinger** [comment]
Where can I find the official MSI Installer of AdoptOpenJDK?

**Comment by baramundi-rklinger** [comment]
> > Hi guys, does anyone know if AdoptOpenJDK will be providing installers for OpenJDK 11, like they do for OpenJDK 8?
> 
> We're working on the installers right now - hopefully, we'll see these rolling out next week.

[Here](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot#x64_win) you can find msi installers für v8. Is msi installer for version 11 planned, too?

**Comment by gdams** [comment]
JDK11 will be shipped very soon. Sorry for the delay!

**Comment by maverick74** [comment]
@gdams Will we get the JDK12 msi with the availability of JDK11 msi as well?

It would be great! JDK12 is planned to be released today :)

**Comment by gdams** [comment]
> Will we get the JDK12 msi with the availability of JDK11 msi as well?

Our official jdk12 release will come out with an MSI at the same time

**Comment by maverick74** [comment]
> Our official jdk12 release will come out with an MSI at the same time.

Great news!!! :D 
Thanks!!!
