### ISSUE TITLE
MSI Updating to 11.0.9.1+1 does not remove 11.0.9.11 (installs alongside instead)

### ISSUE THREAD

**Issue by tushev** [AdoptOpenJDK/openjdk-installer#271]
## Summary

While testing the new release of my [updater](https://github.com/tushev/aojdk-updatewatcher), I noticed that updating via MSI from `11.0.9.11` to `11.0.9.1+1` does not remove `11.0.9.11`. Instead, `11.0.9.1+1` installs alongside.

## Steps to reproduce

1. Get the following MSIs:
```
X:> sha256sum.exe OpenJDK11U-jre_x64_windows_hotspot_11.0.*
c94202eec5a406bf86352270cb0c9c17cb6c3ffc9c7d78c41e67b181e1d6f151 *OpenJDK11U-jre_x64_windows_hotspot_11.0.8_10.msi
77bff0fb5d29f4de560e1be01056fb52b53c139bfe3449e0452a6a226d9b5c7b *OpenJDK11U-jre_x64_windows_hotspot_11.0.9.1_1.msi
d9d155ff0d58c2f821a30f88e0e0d7dfc8a4942c7563d277484c1ae77077fb3e *OpenJDK11U-jre_x64_windows_hotspot_11.0.9_11.msi
```
2. Open [Windows Sandbox](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview). 
2.1 Install `...11.0.9_11.msi`. 
2.2 Install `...11.0.9.1_1.msi`.

## Expected results

Only `C:\Program Files\AdoptOpenJDK\jre-11.0.9.101-hotspot` should be present.

## Actual results

Both `C:\Program Files\AdoptOpenJDK\jre-11.0.9.101-hotspot` and `C:\Program Files\AdoptOpenJDK\jre-11.0.9.11-hotspot` are present.

![image](https://user-images.githubusercontent.com/18406797/100352348-ade3e080-300e-11eb-88b3-8940a4e03fed.png)

## Also noted that

 * Updating from `11.0.8.10` to `11.0.9.1+1` removes `11.0.8.10` correctly.
 * Although `11.0.9.11` had JAVA_HOME feature, `11.0.9.1+1` MSI did not pick it up.
 * Thus, JAVA_HOME remained pointing at `11.0.9.11`

## Triaging info

What is your operating system and platform?
`Windows 10 20H2, Windows Sandbox, x64, JRE`

**Comment by aahlenst** [comment]
@tushev Thanks for filing all those reports.

**Comment by douph1** [comment]
>updating via MSI from 11.0.9.11 to 11.0.9.1+1 does not remove 11.0.9.11. Instead, 11.0.9.1+1 installs alongside
true as documented by MSI limitation 

see
>https://adoptopenjdk.net/installation.html#installers
section "Upgrade limitation:"

**Comment by douph1** [comment]
>Although 11.0.9.11 had JAVA_HOME feature, 11.0.9.1+1 MSI did not pick it up.
>Thus, JAVA_HOME remained pointing at 11.0.9.11

Strange, can someone on windows can confirm ?

**Comment by douph1** [comment]
@tushev can you paste the command line you run to install the new msi via aojdk-updatewatcher ? Did you specify feature level or feature by name ? eg 

INSTALLLEVEL=2 or ADDLOCAL=FeatureMain,..,FeatureJavaHome

**Comment by tushev** [comment]
@douph1 

>can you paste the command line you run to install the new msi via aojdk-updatewatcher ? Did you specify feature level or feature by name ? eg

`Process.Start(MSIFileName);` (C#). It does not specify any features, it relies solely on MSI itself (as it were no updater at all)

I just noticed the issue with updater. Before filing the report, I've confirmed all the steps with manually installing MSIs, in a clean sandbox without any updaters - just by clicking on them in described order.

> Upgrading .msi files works only for the first 3 digits of the build number due to an MSI limitation:

did not know that, thanks!


> Thus, JAVA_HOME remained pointing at 11.0.9.11

I mean, that when I was installing 11.0.9.1+1 MSI, it did not pick up the JAVA_HOME checkbox from 11.0.9.11. Can it be caused by that MSI limitation?

**Comment by douph1** [comment]
>Process.Start(MSIFileName);
I assume this start the GUI right ?

If upgrade like 11.0.8.x to 11.0.9.x then the upgrade process take care of keeping the same option I think.
As upgrade don't work as we know from 11.0.9.x to 11.0.9.y it don't take any option from another install.
So FeatureJavaHome option is not checked by default but I hope that if you check it into the GUI, the later 11.0.9.y will update the JAVA_HOME value

**Comment by tushev** [comment]
@douph1 
>I assume this start the GUI right ?

Yes, it's equivalent to manually clicking or hitting enter in Explorer.

> So FeatureJavaHome option is not checked by default but I hope that if you check it into the GUI, the later 11.0.9.y will update the JAVA_HOME value

Yes, checking that manually updates JAVA_HOME. The issue was - that I expected a fully automated upgrade, so I thought that all options will be picked from the previous install...

OK, thanks! So it seems to be a false positive (known issue).
