### ISSUE TITLE
apt-get update Encountered a section with no Package header

### ISSUE THREAD

**Issue by xoffey** [AdoptOpenJDK/openjdk-installer#288]
Hello Friends in the internet,

I am using debian 10.7 on Arm64 (on an ec2 c6g.large instance)

Following your installation instructions, I did this:
echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster main" | sudo tee /etc/apt/sources.list.d/adoptopenjdk.list
sudo apt-get update

It gives error messages like this:
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/adoptopenjdk.jfrog.io_adoptopenjdk_deb_dists_buster_main_binary-arm64_Packages
E: The package lists or status file could not be parsed or opened.

How can we solve this?

**Comment by aahlenst** [comment]
Odd. I thought I double checked it yesterday after the last releases were uploaded. Either I didn't or it broke afterwards which would be new (but we also got a new version of Artifactory which might have new capabilities). Anyway. I pressed the magic button and it should be working again.
