### ISSUE TITLE
OpenJDK8U-jdk_x64_windows_hotspot_8u282b08.msi Reboots Machine without Warning

### ISSUE THREAD

**Issue by dquam** [AdoptOpenJDK/openjdk-installer#296]
When running the following command:
`msiexec /i "$TEMP\OpenJDK8U-jdk_x64_windows_hotspot_8u282b08.msi" ADDLOCAL=FeatureMain REBOOT=REALLYSUPPRESS INSTALLDIR="$IDOSYSTEM\AdoptOpenJDK\" /quiet /norestart /l*v "$TEMP\AdoptOpenJDK_$TIMESTAMP_RUNTIME.log"`
some machines will reboot without warning. Upon running the same command a second time, the machine will not reboot.

[AdoptOpenJDK_20210128T120434.log](https://github.com/AdoptOpenJDK/openjdk-installer/files/6111977/AdoptOpenJDK_20210128T120434.log) - log with reboot
[AdoptOpenJDK_20210128T123222.log](https://github.com/AdoptOpenJDK/openjdk-installer/files/6111988/AdoptOpenJDK_20210128T123222.log) - second run without reboot

**Comment by aahlenst** [comment]
Are you sure you posted the right logs? They are for 8u252, you seem to want to install 8u282. I cannot find any reason for a reboot in these logs.

Generally, a reboot only happens if files are in use while installing the product.

**Comment by dquam** [comment]
I'm sorry, I thought I had logs from 8u282. I will try to get logs for 8u282. If I can't reproduce it, I will close the issue.

**Comment by karianna** [comment]
Closing this for now, please do re-open if you get a reproducer
