### ISSUE TITLE
Mac Installer to include Mac OS X Java Tools support

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-installer#3]
See https://github.com/AdoptOpenJDK/openjdk-build/issues/321 for the history

**Comment by lenborje** [comment]
(I've entered the very same comment in the referenced thread. Copied here for convenience.)

I don't know if I point out something everybody already knows, but anyway...

When I build the JDK on my Mac, make images builds the requisite MacOS-friendly directory tree under `build/macosx-x86_64-normal-server-release/images/jdk-bundle/jdk-11.jdk/`, in addition to the "standard linux tree" under `build/macosx-x86_64-normal-server-release/images/jdk/`:

```
$ tree -L 3 build/macosx-x86_64-normal-server-release/images/jdk-bundle/jdk-11.jdk
build/macosx-x86_64-normal-server-release/images/jdk-bundle/jdk-11.jdk
└── Contents
    ├── Home
    │   ├── bin
    │   ├── conf
    │   ├── demo
    │   ├── include
    │   ├── jmods
    │   ├── legal
    │   ├── lib
    │   ├── man
    │   └── release
    ├── Info.plist
    └── MacOS
        └── libjli.dylib -> ../Home/lib/jli/libjli.dylib
$ tree -L 1 build/macosx-x86_64-normal-server-release/images/jdk
build/macosx-x86_64-normal-server-release/images/jdk
├── bin
├── conf
├── demo
├── include
├── jmods
├── legal
├── lib
├── man
└── release

```
So it seems to that a "correct" MacOS installation archive could be created by simply selecting the `jdk-bundle` sub-directory when creating it.

**Comment by lenborje** [comment]
A trivial command example which builds an unsigned PKG installer from the `jdk-bundle`:

`$ pkgbuild --root build/macosx-x86_64-normal-server-release/images/jdk-bundle/jdk-11.jdk --install-location /Library/Java/JavaVirtualMachines/jdk-11.jdk --identifier net.adoptopenjdk.openjdk --version 11.0.0 build/macosx-x86_64-normal-server-release/OpenJDK-11.pkg`

A 'real' pkg should of course be correctly signed, probably have another identifier, etc etc.

**Comment by gdams** [comment]
@lenborje this looks really interesting, let's try and jump on a call sometime and investigate this further.

**Comment by rubin55** [comment]
Is there any progress on this? I would like to transition to AdoptOpenJDK for my Development needs since coming 25th will be a new world for Java development in general (Java 11 becomes stable, anything prior to that is now not publicly supported anymore so I don't want to run an Oracle JVM -> what are my options -> AdoptOpenJDK). 

This issue is surprisingly blocking to a macos user :-)

**Comment by karianna** [comment]
@rubin55 A volunteer will have to pick this up - the core team is still working on some cross platform infra and build issues.

**Comment by lenborje** [comment]
What is needed? As I’ve shown above, it is trivial to create an unsigned installer pkg. I have zero knowledge of how the build infrastructure is set up, so I do not know what is missing there. You would need an active Apple Developer account to sign the package, but apart from that, I guess it would only require an additional one-liner statement in a build script.

**Comment by rubin55** [comment]
For those who want to run the currently provided AdoptOpenJDK as downloadable at https://adoptopenjdk.net/ , Here are some pointers. The below is tested with the current latest OpenJDK with HotSpot, version 1.8.0 r172 for MacOS:

Make sure you have root privileges:

0. First make sure you don't currently have a JDK 8 at `/Library/Java/JavaVirtualMachines/1.8.0.jdk`
1. Download [OpenJDK8_x64_Mac_jdk8u172-b11.tar.gz](https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/jdk8u172-b11/OpenJDK8_x64_Mac_jdk8u172-b11.tar.gz)
2. Download my hand-crafted [Info.plist.zip](https://github.com/AdoptOpenJDK/openjdk-installer/files/2354594/Info.plist.zip)
3. Create directory: `mkdir -p /Library/Java/JavaVirtualMachines/1.8.0.jdk/Contents/MacOS`
4. Enter directory: `cd /Library/Java/JavaVirtualMachines/1.8.0.jdk/Contents`
5. Unpack the archive: `tar xzf /full/path/to/downloaded/OpenJDK8_x64_Mac_jdk8u172-b11.tar.gz`
6. Rename the directory: `mv jdk8u172-b11 Home`
7. Unpack the Info.plist: `unzip /full/path/to/downloaded/Info.plist Info.plist`
8. Enter directory: `cd MacOS`
9. Link JNI library: `ln -s ../Home/jre/lib/jli/libjli.dylib`
A. Check if AdoptOpenJDK shows up: `/usr/libexec/java_home -V`
B. Start another (non-root) terminal, run: `export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)`
C. After that, verify the running Java version: `java -version`

The above was tested with various Java command line tools, like maven, javac. Additionally, I've tested various Java graphical applications, like Eclipse and MuleSoft Anypoint Studio.

**Comment by karianna** [comment]
@lenborje We have an Apple developer account and we do sign the existing Mac binaries.  Are you a member on our #build channel in slack?

**Comment by lenborje** [comment]
No, I’m not. What’s the URL?

**Comment by karianna** [comment]
@lenborje https://www.adoptopenjdk.net/slack.html

**Comment by nordligulv** [comment]
Thanks @rubin55 !

Today I decided to migrate to AdoptOpenJDK on my mac from OracleJDK because of recent news. I installed it with homebrew but everything went broken since /usr/libexec doesnt recognize it.

So I wrote a small [script](https://gist.github.com/nordligulv/f9da7b89f82286b49077d2df9006455a) to install latest AdoptOpenJDK 10 on macos following @rubin55 's instructions. Now everything works as before. Hope that helps others as well.

**Comment by breun** [comment]
I'm the maintainer of the OpenJDK ports in MacPorts. I'm currently using Oracle's OpenJDK builds, but I'm considering AdoptOpenJDK's builds.

I think it would be great if the AdoptOpenJDK releases for macOS would be ready to go when unpacked under `/Library/Java/JavaVirtualMachines`, just like the Oracle OpenJDK builds, because otherwise MacPorts would have to duplicate the stuff the installer does in order to construct the directory structure expected by these macOS tools.

**Comment by karianna** [comment]
I think we might have to bite the bullet and go with cask...  We can follow the similar recipe other OpenJDK and Oracle JDK casks

**Comment by breun** [comment]
Ah, I see that the AdoptOpenJDK binaries for macOS now use the directory layout expected by macOS tools: https://blog.adoptopenjdk.net/2018/10/macos-binary-changes

**Comment by karianna** [comment]
Yes, we're pushing out one last release and then we'll update the homebrew tap's here and the casks at homebrew-core (and deprecate our tap versions in due course).

**Comment by gdams** [comment]
closing as the installers now work with this
