### ISSUE TITLE
Double-click on JAR doesn't launch the application 

### ISSUE THREAD

**Issue by xtbe** [AdoptOpenJDK/openjdk-installer#32]
(Moved to here as #684 was closed)

When you double-click on a JAR the application it contains doesn't launch.
This is different behavior compared to the Oracle JDK/JRE. With this version this works.

Tested on Windows 10 x64

**Comment by todivefor** [comment]
This same issue exists for Mac OS X.  With Oracle JDK/JRE, the jar is associated with "jar launcher.app" (15.0.1).  This app will not launch an AdoptOpenJDK created JAR.
