### ISSUE TITLE
What is OpenJDK Installer from OpenJDK-FileLess?

### ISSUE THREAD

**Issue by keito940** [AdoptOpenJDK/openjdk-installer#33]
Hi. I Am Considering using AdoptOpenJDK.
...But I thought that I decompressed the archive and fiddled with the system a bit, I asked this question.
Is it possible to install AdoptOpenJDK even if there is no OpenJDK file in the future?
Also, is there a mechanism to install even at Java runtime only?

**Comment by karianna** [comment]
Hi @keito940 - you can download a tar.gz or zip bundle from our website today.  Both JDK and JRE options are available.  Does that meet your needs?

**Comment by karianna** [comment]
Ah, I see what you mean.  Yes we will be building operating system specific installers for AdoptOpenJDK (MSI, DMG, RPM et al)
