### ISSUE TITLE
Looking for the AdoptOpenJDK 8u202 MSI file and define settings

### ISSUE THREAD

**Issue by zyxser** [AdoptOpenJDK/openjdk-installer#45]
Hi guys,

I have been asked to prepare a deployment package with AdoptOpenJDK in my company since we are looking for an alternative solution to the Oracle Java releases. The thing is I am not able to find the MSI file for the AdoptOpenJDK 8u202 as am willing to deploy this package through SCCM and automate everything as much as I can. 

Another topic is how can I change the settings of the package. E.g: with Oracle Java I send a report with the settings I want to apply to the Java Package: "Check for Updates Automatically", "Security Levels", "Advanced settings", etc, etc. Then this is configured as default in the Java deployment package. But with the AdoptOpenJDK I not sure how to do this or at least know which settings are available. 

Thanks for your support.

**Comment by karianna** [comment]
The first Windows MSI installer was released today for OpenJ9 binaries.  We are continuing to work on these for HotSpot as well.  Please see the current Wix based installer in the source code here in the openjdk-installer project for its existing state and options.

**Comment by douph1** [comment]
There is not anymore  JavaWebStart and so no "Security Levels", "Advanced settings" which was aimed to configure JWS (No more ControlPanel)

**Comment by douph1** [comment]
"Check for Updates Automatically" is not yes implemented

**Comment by don-vip** [comment]
@douph1 see #22 for Java WebStart discussions.

**Comment by alexhass** [comment]
@zyxser: If you open the package with an MSI editor you see that everything is customizable via features with an MST file.

**Comment by maverick74** [comment]
There is also #27 ( Provide MSI installer ) that might interest you

**Comment by maverick74** [comment]
@karianna is there any ETA for the OpenJDK 11 (LTS)?

We are interested in that version.

Concerning auto-updates... does the recent MSI has support for it?

**Comment by karianna** [comment]
> @karianna is there any ETA for the OpenJDK 11 (LTS)?
> 
> We are interested in that version.
> 
> Concerning auto-updates... does the recent MSI has support for it?

It'll take a week or two to iron out all of the MSI issues and make it a regular part of our pipelines.  One of those challenges is looking at the auto-update.  If you do have expertise in this area please do jump on our slack channel

**Comment by alexhass** [comment]
Auto update is somewhat difficult here. People need to be able to install several version in parallel. This affects both jdk and jre. This means the msi internal upgrade feature may not used.

For software that do not require parallel installation this is easy. I‘ve done this a lot, but this installer was challenging as it requires parallel installations.

I‘m not sure ww can add a screen that asks the user if he want to upgrade or do a parallel installation and than really do what the user selected. Never done this... maybe with custom action, but here I‘m out and cannot help.

**Comment by karianna** [comment]
Yes, I'm also torn on this.  As a JDK power user, I have 30-40 different versions on purpose.  I guess an end user really only wants the one though...  It would be great to give them a choice but as you say I'm not sure the Wix installer can even do that.

**Comment by douph1** [comment]
@alexhass 
When you says
>This means the msi internal upgrade feature may not used.
and
>as it requires parallel installations

Is it linked with the actual code who generate always new GUID/CLSID for each build ? So whe can have several install of same major(8/11) arch(32/64) jvm(hotspot/openj9) ( 8_x64_openj9 ) and different minor build ?

`
 REM Generate one ID per release. But do NOT use * as we need to keep the same number for all languages, but not platforms.

    FOR /F %%I IN ('POWERSHELL -COMMAND "$([guid]::NewGuid().ToString('b').ToUpper())"') DO (
      SET PRODUCT_ID=%%I
      ECHO PRODUCT_ID: !PRODUCT_ID!
    )
    FOR /F %%F IN ('POWERSHELL -COMMAND "$([guid]::NewGuid().ToString('b').ToUpper())"') DO (
      SET PRODUCT_UPGRADE_CODE=%%F
      ECHO PRODUCT_UPGRADE_CODE: !PRODUCT_UPGRADE_CODE!
    )
`
Personally, I expect that when I downloading a new version of same major package it update (replace) the current one to not having many old version.
If I whant to keep/test in parallel old minor release, I use the archive format tgz/zip ..

I think whe need to use the same CLSID/guid for each minor build of same major/arch/jvm.
It will replace b191 with b201 for same major(8/11) arch(32/64) jvm(hotspot/openj9)
but allow to install 8/32/hotpost and 8/32/openj9 and 11/64/hotpost and etc ..

**Comment by douph1** [comment]
@karianna , when you says
>I have 30-40 different versions on purpose

**Comment by douph1** [comment]
Also, we must thinking of what we really need/want:
 * Auto-update 
 * or just notifier who says : hello a new version is available  (like ojdkbuild)

**Comment by karianna** [comment]
> @karianna , when you says
> 
> > I have 30-40 different versions on purpose
> 
> Do you mean all installed with MSI ?
> or do you use zip ?

I'm on a Mac, so all installed via Brew or manually.

**Comment by maverick74** [comment]
As an "end user" we only keep one version and it would be great to have it always updated.

So, for us, an auto-update would be great!

However, we have nothing against the possibility for it to be disabled on settings.

**Comment by douph1** [comment]
Since now (https://github.com/AdoptOpenJDK/openjdk-installer/pull/74 was merged)
next MSI will provide upgrade to new AdoptOpenJDK for same bundle type jre/jdk-8/11-hotspot-openj9 ( remove previous one at the end of the installation (to keep only the newer one) )
(This is not a option)
(Downgrade is not allowed ( without first uninstalling the new one ) )

**Comment by douph1** [comment]
@zyxser  have you tried successfully to
>deploy this package through SCCM 

?

**Comment by maverick74** [comment]
> Since now (#74 was merged)
> next MSI will provide upgrade to new AdoptOpenJDK for same bundle type jre/jdk-8/11-hotspot-openj9 ( remove previous one at the end of the installation (to keep only the newer one) )
> (This is not a option)
> (Downgrade is not allowed ( without first uninstalling the new one ) )

I'm not getting it.

will we get notified a new version is available?
will we be able to choose "update now"?
and after the update will we be asked if we would like to remove older versions?

Sorry for so many questions

**Comment by alexhass** [comment]
Past installers created by me intentionally allowed to install several versions in parallel. This is no longer possible. The setup itself upgrades outdated versions. This is a common practice for setups, but Oracle JDK does allow parrallel installs.

This are build in mechanisms of msi. This does not mean there exists an automatic update or a notification.

Hopefully we can close the issue so the questions from people who comment before reading are stopping.

**Comment by gdams** [comment]
@alexhass the change that was recently implemented essentially means that you cannot have several versions of the same java version in parallel. You can still have a Java 8 and a Java 11 and even a Java 8 OpenJ9 at the same time and they won't be overwritten.

**Comment by gdams** [comment]
@maverick74 I can answer your questions for the current installers

>will we get notified a new version is available?

No, this is what an autoupdater will do. We plan to implement this but it's not available now. See https://github.com/AdoptOpenJDK/openjdk-installer/issues/4

> will we be able to choose "update now"?

Once the autoupdater is implemented it will work like this yes.

> and after the update will we be asked if we would like to remove older versions?

Our MSI's are now configured to automatically remove the older version if it is the same java version, vm and architecture.

**Comment by MarkRx** [comment]
Example installing with CLI:

> msiexec /i OpenJDK8U-jdk_x64_windows_hotspot_8u212b03.msi ADDLOCAL=FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome INSTALLDIR="C:\temp" /q

Features (use with ADDLOCAL):
- FeatureEnvironment
- FeatureJarFileRunWith
- FeatureJarFileRunWith
- FeatureMain
- FeatureOracleJavaSoft

**Comment by douph1** [comment]
Please refere to updated README.md  (FeatureMain is required)
https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/wix/README.md

There is just documentation about "Per user install" which is new into installer and not any jdk are already built with this new capability

**Comment by alexhass** [comment]
You should never create a per user installer! Biggest bullshit ever. It only causes issues.

**Comment by karianna** [comment]
@zyxser Does that cover off all of your requirements?

**Comment by ajones009** [comment]
Not sure this is the place to post this, but how do I go about utilizing a site exception list? Im not having much luck in the Control Panel.  Thank you!

**Comment by aahlenst** [comment]
Looks like the problem was solved. Please reopen if you feel otherwise.
