### ISSUE TITLE
Document this repository

### ISSUE THREAD

**Issue by don-vip** [AdoptOpenJDK/openjdk-installer#5]
There is nothing explaining how to build the installer.

**Comment by don-vip** [comment]
I guess this is the one issue we cannot help with. @gdams as you made all commits on this repository you are probably the only one able to document what is needed to build the installer. This will help everyone to help on other issues.

**Comment by alexhass** [comment]
Does https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/wix/readme.TXT fit?

**Comment by karianna** [comment]
@alexhass That would form some of the doc set, but we need something that ties all of the docs for all of the potential installers.

**Comment by alexhass** [comment]
How many installers do you expect? Windows should have only one and that is added now.

**Comment by karianna** [comment]
Mac, RPM, .deb, possibly others

**Comment by karianna** [comment]
OK, so @gdams told me that there's a CI job which runs a tool which goes over the XML doc and builds various installers.  We're going to have a hack session next week to try and get this into the pipelines (including the MSI).

**Comment by gdams** [comment]
closing as the pkgbuild and wix installers are well documented now
