### ISSUE TITLE
Define JAVA_HOME and JRE_HOME behaviour in msi installers

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-installer#50]
The AdoptOpenJDK msi installers currently
1. Set JAVA_HOME when installing the jdk, disabled by default
2. Set JRE_HOME when installing the jre, disabled by default

So far I have only been able to identify Tomcat as an application which uses JRE_HOME.

There are many applications which use JAVA_HOME, (including Tomcat if JRE_HOME is not set), but the AdoptOpenJDK jre installer does not offer this as an option.

One approach might be to offer setting both JRE_HOME and JAVA_HOME when installing the jre?

@alexhass - when you originally provided the msi installer code, what was the rationale behind the current JAVA_HOME and JRE_HOME options?

For reference, this is the behaviour of other installers taken from a thread by @douph1 in the installer slack channel:

Installer who propose to set JAVA_HOME :
* Azul Zulu : dont
* Java.com (JRE): dont
* Oracle.com (JDK): dont
* Liberica Bellsoft : dont
* Amazon Corretto : YES as an option ENABLED by default
* OJDK (RedHat) : YES as an option DISABLED by default
* AdoptOpenJDK (currently): YES as an option DISABLED by default

Installer who propose to set JRE_HOME
* AdoptOpenJDK (currently) : instead of JAVA_HOME if build is JRE not JDK (edited)

**Comment by alexhass** [comment]
I only followed Oracle documentation when I added JRE_HOME. It‘s easy to add both if needed. I changed thos very late as I never heard of this in my life. I‘m also fine to replace it if this ist best practice.

**Comment by lumpfish** [comment]
So if the only application we know which uses JRE_HOME is Tomcat, and Tomcat works anyway if JAVA_HOME is set, and we know lots of applictions use JAVA_HOME, then I suggest we set JAVA_HOME for both jdk and jre and never set JRE_HOME.  Any support for this or alternative views?

**Comment by douph1** [comment]
100% Ok, Only JAVA_HOME
Other exemple:
IDEA IntelliJ use : Try (in order): IDEA_JDK, idea.jdk, ./jre64, JDK_HOME, JAVA_HOME, "java" in PATH.
Gradle : use JAVA_HOME
...

**Comment by alexhass** [comment]
Ok

**Comment by lumpfish** [comment]
@gdams, @karianna - are you in agreement?  If so, @gdams , can you include this with the other work you're doing on installers at the moment or would you like a PR?

**Comment by karianna** [comment]
I'm happy about your decision :-).  If the majority of users complain later we can revisit.

PR would be welcome.

**Comment by douph1** [comment]
done through
