### ISSUE TITLE
Looking for MSI Package that supports GPO

### ISSUE THREAD

**Issue by demiced** [AdoptOpenJDK/openjdk-installer#57]
Hello together,

I'm looking for an OpenJDK MSI package that specifically supports software deployment (GPO). Unfortunately the MSI package ,,OpenJDK8U-jre_x64_windows_hotspot_8u202b08" does not work. So far it can't be deployed via the GPO.  Has one of you made experiences and provided such MSI packages already in companies? I had already tried to change parameters with .mst files. So far nothing had worked.

**Comment by gdams** [comment]
have you read https://github.com/AdoptOpenJDK/openjdk-installer/tree/master/wix#deploy-via-active-directory-gpo?

**Comment by douph1** [comment]
Hi @demiced,
Have you tried install per user or per machine ?
Can you enable logging ?
https://www.advancedinstaller.com/user-guide/qa-log.html#automated-logging

**Comment by demiced** [comment]
Yes @gdams  I have read that.

If I enter the command via the CMD console, it works:

`msiexec /i "Z:\Softwarebereitstellung\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi" /L*V "C:\log\OpenJDK.log"`

But how can I implement the parameters in the GPO? 

See Picture Link:
https://s15.directupload.net/images/190228/vktjb5to.jpg

I don't have the possibility to specify this in the software deployment. Do I need the softwareinstaller then ( [advancedinstaller.com](url)  ) ?

The GPO works and gpresult say that too. I have try it to install per user policy. But I also tryed it per computer policy. Nothing works. The only thing I see in the task manager is this:

https://s16.directupload.net/images/190228/gwn5uxcr.jpg

I have also try a modification with a .mst file (Orca) and try to add this parameter:

https://s15.directupload.net/images/190228/8xip6t6w.jpg

**Comment by demiced** [comment]
@douph1 I have enable live logging. But I not found a MSI*.log under C:\Windows\Log and AppData/Local/Temp

**Comment by douph1** [comment]
and in "Windows\Temp" ?

As I have read, you normally will be able to customise property with MST.
But if it don't work without MST .. there is a problème elsewhere.

Maybe you need this 
Computer Configuration > Policies > Administrative Templates > Windows Components> Window Installer > Always install with elevated privileges

**Comment by douph1** [comment]
PS: I have seen that Windows Defender can take a while to scan(analyse in sandbox) all the JRE/JDK classes after download .. Maybe Windows defender do the same during install ? Have you seen high cpu usage from your AV. It can take very long time.

**Comment by demiced** [comment]
@douph1 Unfortunately I wasn't able to find any logfiles on Windows\Temp.

> Computer Configuration > Policies > Administrative Templates > Windows Components> Window Installer > Always install with elevated privileges

I have already set this in the GPO. 

> I have seen that Windows Defender can take a while to scan(analyse in sandbox) all the JRE/JDK classes after download .. Maybe Windows defender do the same during install ? Have you seen high cpu usage from your AV. It can take very long time.

I've tried that now. Windows Defender is now completely disabled. I also don't have any other anti-virus systems on it anymore. Unfortunately the same result. I haven't noticed anything about high processes so far...

I also tried to add the GPO in other network systems. But nothing happens here either. Other .msi packages already worked with the same settings and installed XMLNotepad automatically on my clients.

I think it's the MSI package. After all, other .msi packages can also be installed.

Thanks in advance

**Comment by gdams** [comment]
@douph1 any ideas?

**Comment by douph1** [comment]
Any log from MsiInstaller in Event Log ?Open Computer management -> event viewer -> Windows Logs - Application

You're looking for errors with a source of MsiInstaller (and any other events that get logged at the same time of course).

Finally, a lot of applications record their own log as part of the installation process. If you can find the local folder that the MSI installation was ran from then there may be a detailed error log inside that (of course, if you can find errors in the windows event viewer then this will hopefully also mention the application logfile and tell you where to find it)

**Comment by demiced** [comment]
**Client1:**

Error1:

> Product: AdoptOpenJDK JRE with Hotspot 8.0.202.08 (x64) -- Installation failed.

Error2:

> The product was installed by Windows Installer. Product name: AdoptOpenJDK JRE with Hotspot 8.0.202.08 (x64). Product version: 8.0.202.08. Product language: 1031. Manufacturer: AdoptOpenJDK. Success or error status of the installation: 1602.

https://docs.microsoft.com/en-us/windows/desktop/msi/error-codes
In this website stands Code 1602 for:

ERROR_INSTALL_USEREXIT | 1602 | The user cancels installation.


But I think this is the error message because I shut down the system and cancelled the installation after 5 hours... There are otherwise no error messages

**Client2:**

- 0 Reports

**Comment by gdams** [comment]
@demiced have you tried with the `/quiet` param? seemed to install okay for me

**Comment by demiced** [comment]
I have execute the command on two Clients:

`msiexec /i "Z:\Softwarebereitstellung\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi" /L*V "C:\log\OpenJDK.log" /quiet` (It works with Client 2)

The command does not work on Client 1 for me and the MSI package is not installed. The OpenJDK.log contains the following: 

> === Verbose logging started: 08.03.2019  15:27:44  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\WINDOWS\system32\msiexec.exe ===
MSI (c) (70:14) [15:27:44:588]: Resetting cached policy values
MSI (c) (70:14) [15:27:44:588]: Machine policy value 'Debug' is 0
MSI (c) (70:14) [15:27:44:588]: ******* RunEngine:
           ******* Product: Z:\Softwarebereitstellung\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (70:14) [15:27:44:588]: Client-side and UI is none or basic: Running entire install on the server.
MSI (c) (70:14) [15:27:44:588]: Grabbed execution mutex.
MSI (c) (70:14) [15:27:44:713]: Cloaking enabled.
MSI (c) (70:14) [15:27:44:713]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (70:14) [15:27:44:713]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (A4:BC) [15:27:44:744]: Running installation inside multi-package transaction Z:\Softwarebereitstellung\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi
MSI (s) (A4:BC) [15:27:44:744]: Grabbed execution mutex.
MSI (s) (A4:5C) [15:27:44:744]: Resetting cached policy values
MSI (s) (A4:5C) [15:27:44:744]: Machine policy value 'Debug' is 0
MSI (s) (A4:5C) [15:27:44:744]: ******* RunEngine:
           ******* Product: Z:\Softwarebereitstellung\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (s) (A4:5C) [15:27:44:744]: Note: 1: 2203 2: Z:\Softwarebereitstellung\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi 3: -2147287037 
MSI (s) (A4:5C) [15:27:44:744]: MainEngineThread is returning 3
MSI (s) (A4:BC) [15:27:44:744]: User policy value 'DisableRollback' is 0
MSI (s) (A4:BC) [15:27:44:744]: Machine policy value 'DisableRollback' is 0
MSI (s) (A4:BC) [15:27:44:744]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (A4:BC) [15:27:44:760]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (A4:BC) [15:27:44:760]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (A4:BC) [15:27:44:760]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (70:14) [15:27:44:760]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (70:14) [15:27:44:760]: MainEngineThread is returning 3
=== Verbose logging stopped: 08.03.2019  15:27:44 ===

Has any of you ever tried to really provide this via group policy as software deployment and not execute it via the msiexec command? Has it worked for any of you via software deployment?

If the installation works via msiexec on Client2, why doesn't it work via software deployment in the GPO?

Am I the only one where it doesn't work via the group policy or is there someone who has already done this successfully?

**Comment by douph1** [comment]
>Has any of you ever tried to really provide this via group policy as software deployment and not execute it via the msiexec command?

no

>why doesn't it work via software deployment in the GPO?
As it works on "Client 2" and not "Client 1" try to compare thes two logs files.
Same msi installer version  ?

you got error number **2203**  **-2147287037**

MSI (s) (A4:5C) [15:27:44:744]: Note: 1: **2203** 2: Z:\Softwarebereitstellung\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi 3: -2147287037


Some hint : 
https://discuss.newrelic.com/t/problem-installing-agent-msi-2203-2147287038/38975
>I found the problem.
The file wasn’t actually there.

https://answers.microsoft.com/en-us/windows/forum/all/system-error-2147287037-when-uninstalling-or/e0272e50-e7bd-4d2c-a585-e0fb34a9658f
>-2147287037 = 0x80030003
//
// MessageId: STG_E_PATHNOTFOUND 
//
// MessageText:
//
// The path %1 could not be found.
//
#define STG_E_PATHNOTFOUND               _HRESULT_TYPEDEF_(0x80030003 L)

https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000P9x8SAC

Maybe your Z:\ (network folder) is not available for System account on "Client 1" ?
Can you try with a local path ? like C:\Temp\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi"
or a network share \\computer\share\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi

**Comment by douph1** [comment]
with /i package.msi /quiet
* Normal cmd dont work, you must run cmd as administrator

I have tried with  System account : ( run via cmd as administrator privilege)
>PSTools>PsExec.exe -i -s cmd
-s | Run the remote process in the System account.
("AUTORITE NT\Système" in french)
  Like by GPO I think

And It's work too an set AdoptOpenJDK in path

So `msiexec /i package.msi /quiet` work ( only on administrator or "system" account .. not with normal user because of UAC probably )

**Comment by demiced** [comment]
> Maybe your Z:\ (network folder) is not available for System account on "Client 1" ?
> Can you try with a local path ? like C:\Temp\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi"
> or a network share \computer\share\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi

`msiexec /i "\\PRD-ADS-001\Gemeinschaftsdaten\Softwarebereitstellung\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi" /L*V "C:\log\OpenJDK.log" /qn`

@douph1 With this command works, thanks. 

But in the GPO I have this file path: _\\PRD-ADS-001\Gemeinschaftsdaten\Softwarebereitstellung\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi_ and it's not working.

I have run the CMD console with Administrator-privileges. I even turned out UAC for the group policy to check if the error still exist. Unfortunately to no avail. 

My goal is to automatically install the MSI-Package on any number of clients using the GPO. 

Is it possible to implement these features in the upcoming versions for the MSI-Package? We would like to avoid using a scipt because it wouldn't give us the flexibility we need.

**Comment by LukWlbr** [comment]
Hello everybody,

I've noticed the same problem.
It'd be great if the msi package could be rolled out on all my clients without an additional script.

dear greetings
-Luk

**Comment by douph1** [comment]
I will be happy to help you if you can tell us what is wrong with the installer and / or how to fix it.

**Comment by demiced** [comment]
The problem is that we want to automatically distribute the msi package to all our clients via the  group policy. 
But unfortunately no AdoptOpenJDK will be installed. 

When I try to install the package from the command line via msiexec, it works fine.
But we want to install the msi package without an additional script.

If we try to distribute other msi-packages like Adobe Reader using the same method, this works fine.

This is the method that works with any other MSI package. But not with the AdobtOpenJDK package:
 
![openjdk1](https://user-images.githubusercontent.com/48058083/56360282-7da65000-61e4-11e9-9aaf-42a64a3b6e86.jpg)

**Comment by douph1** [comment]
@demiced I understand it is not functionning, but you dont tell us what is the reason and I dont have nor chrystall ball nor active directory to debug.

Previously I have asked if you can try deploying via policy with a local file:
>Maybe your Z:\ (network folder) is not available for System account on "Client 1" ?
>Can you try with a local path ? like C:\Temp\OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi"

And I see in your screenshot you user a remote path  \\PRD-ADS-001\...

Can you try to get le installer in local C:\Temp
Adjust policy to point to C:\Temp\installer.msi
and then give us some Windows Installer verbose log or policy deploy log with an error message ... or something ... ?

**Comment by gdams** [comment]
@douph1 let's try and set up an active directory server that you can run some tests with. I've also asked someone from Microsoft to take a look at this.

**Comment by brunoborges** [comment]
@gdams can you pls paste here the URL for the specific MSI installer people are having problem with?

**Comment by gdams** [comment]
all of them, here is an example though: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b03/OpenJDK8U-jdk_x64_windows_hotspot_8u212b03.msi

**Comment by douph1** [comment]
@demiced  can you try to edit the downloaded MSI and change Property->ProductLanguage to 0
and retry ?

**Comment by bursped** [comment]
>But unfortunately no AdoptOpenJDK will be installed

Have you disabled language check?

![2019-05-03 12_31_03-Erweiterte Bereitstellungsoptionen](https://user-images.githubusercontent.com/50200173/57132322-862f8680-6d9f-11e9-9452-b38e15aead75.png)

**Comment by douph1** [comment]
@demiced  due to the fact that the msi is big, maybe you need something like

**Comment by burMarc** [comment]
Hi,

the simple way to test if the GPO will install something is "gpupdate /force". If there is only the message that Computer- and User-Policy is updated, he doesn't install something. There must be a message that he want deploy some software and then asks for reboot.

**Comment by douph1** [comment]
@demiced can you try to deploy MSI via Computerkonfiguration and not Benutzerkonfiguration please ?
And ensure that your network drive/share is available at computer start ( not user logon )
because the installer is designed to install only one AdoptOpenJdk per computer : see https://github.com/AdoptOpenJDK/openjdk-installer/issues/103

And take a look about this comment here :
https://github.com/AdoptOpenJDK/openjdk-installer/issues/101#issuecomment-489545993

IE: dont forget to set INSTALLDIR variable and to enable "FeatureMain"

**Comment by NickETH** [comment]
Hi demiced,
Doing a user based installation of JRE does not make sense at all!
Things like JRE can be considered as basic software and should be installed computer based.
GPO-Installation of AdoptOpenJDK with a Computer configuration GPO works like everything else.
Just moved a small office from Oracle JRE to AdoptOpenJDK JRE with GPO install with no problems at all.
Important: As burMob pointed out, you have to check to ignore the language, because GPO install does not like embedded language transforms.
If you need to install a language other than English, you would have to extract the language transform and supply it, when you are preparing the GPO for installation.
To troubleshoot an MSI installation, allways look for the MSI log. You have to enable it with another GPO setting. Just search online for “voicewarmupx” and you will find help to enable it.
Nick

**Comment by demiced** [comment]
Hello, everybody,

I'm very happy to have your help! We managed to install the MSI package via Group Policy. 

The problem was the ,,language check". We have disabled it now and it works fine.

Thank you very much!

**Comment by aahlenst** [comment]
Looks like the problem was solved and there's no action to take on our side. Please reopen if you feel otherwise.
