### ISSUE TITLE
MSI: Same install folder ( by default ) for hotspot and openj9 crash jvm

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/openjdk-installer#58]
Both OpenJDK8U-jre_x64_windows_hotspot_8u202b08.msi
and OpenJDK8U-jre_x64_windows_openj9_8u202b08_openj9-0.12.1.msi
extract JRE in same directory 
C:\Program Files\AdoptOpenJDK\jre-8.0.202.08\
which lead to crash because of mix of JRE ..

To reproduce:
install openj9, then install hotspot ( keeping default directory proposed by the installer )
```
C:\Users\adminup>java -version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000000000000, pid=4228, tid=0x0000000000001040
#
# JRE version:  (8.0_202-b08) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.202-b08 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000000000
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\adminup\hs_err_pid4228.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```
The installer must propose a directory name like that : [jre|jdk]-version-*[hotspot|openj9]*

**Comment by douph1** [comment]
Installer dont warn about the existing folder
Same problem with JDK 
OpenJDK8U-jdk_x64_windows_hotspot_8u202b08 
and
OpenJDK8U-jdk_x64_windows_openj9_8u202b08_openj9-0.12.1
both install by default into
C:\Program Files\AdoptOpenJDK\jdk-8.0.202.08\

**Comment by douph1** [comment]
And same pb for package x86 (32b)
Hotspot and openj9 share same directory by default (C:\Program Files (x86)\AdoptOpenJDK\jre-8.0.202.08\)  without erasing directory but just append to it 

C:\Users\adminup>java -version
<error: unable to load java (La procédure spécifiée est introuvable. )>

**Comment by gdams** [comment]
I would suggest that we append `-openj9` or `-hotspot`
