### ISSUE TITLE
[MSI] Need to keep same ProductCode for each installer

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/openjdk-installer#59]
Currently wix/Build.OpenJDK_generic.cmd generate always a new MSI ProductCode

    FOR /F %%F IN ('POWERSHELL -COMMAND "$([guid]::NewGuid().ToString('b').ToUpper())"') DO (
      SET PRODUCT_UPGRADE_CODE=%%F
      ECHO PRODUCT_UPGRADE_CODE: !PRODUCT_UPGRADE_CODE!
    )

This prevent MSI to upgrade.

See http://wixtoolset.org/documentation/manual/v3/howtos/updates/major_upgrade.html
https://docs.microsoft.com/fr-fr/windows/desktop/Msi/major-upgrades

**Comment by gdams** [comment]
@douph1 are you able to fix this for us?

**Comment by douph1** [comment]
Actual UpgradeCode by installer 
{F8C51698-5891-442D-AE70-5A0C20AC7A8D} OpenJDK8U-jre_x64_windows_hotspot_8u202b08
{8C335E26-3838-4BC9-B144-8AA07CEF6605} OpenJDK8U-jre_x64_windows_openj9_8u202b08_openj9-0.12.1
{A228317F-6ABD-4CEA-9725-745C5D2CF5B1} OpenJDK8U-jdk_x64_windows_hotspot_8u202b08
{CC9D4E2E-6C34-440C-A250-D95836053D7C} OpenJDK8U-jdk_x64_windows_openj9_8u202b08_openj9-0.12.1
{2E440B36-6F64-4F16-964B-05AE5807F77E} OpenJDK8U-jre_x86-32_windows_hotspot_8u202b08
{B7C8707D-104B-44E7-AD66-803D6EA447FB} OpenJDK8U-jre_x86-32_windows_openj9_8u202b08_openj9-0.12.1
{D606C316-4CCD-4D55-9925-A2942FC8F4EF} OpenJDK8U-jdk_x86-32_windows_hotspot_8u202b08
{1771CB0B-D73C-43E5-928C-C0E2F93215AA} OpenJDK8U-jdk_x86-32_windows_openj9_8u202b08_openj9-0.12.1

**Comment by douph1** [comment]
@gdams maybe if it is what we really want ..

**Comment by gdams** [comment]
current proposal is to take the sha256 of the release name and set the upgrade code to be that.
