### ISSUE TITLE
Create msi installer for jdk11

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-installer#60]
There are msi installers on the AdoptOpenJDK release download page for jdk8 but not for jdk11.

**Comment by lumpfish** [comment]
Looks like the jobs might be in the pipeline but failing: https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/

**Comment by ben-walsh** [comment]
Failures in the https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows job have now been resolved for JDK11 openj9 and hotspot builds.
See JDK11 pipeline jobs https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/347 and https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/343 as examples.

**Comment by gdams** [comment]
should be good to go if someone pushes a new release of jdk11

**Comment by douph1** [comment]
Installer for JKD11 is out
