### ISSUE TITLE
Provide CurrentVersion registry key

### ISSUE THREAD

**Issue by slide** [AdoptOpenJDK/openjdk-installer#63]
Currently, the MSI installed creates some registry keys to specify the JAVA_HOME for a specific version. It would be useful to have a CurrentVersion key at the HKLM\SOFTWARE\$(var.ProductManufacturer)\$(var.ProductCategory) level which tells what the current latest installed version (default version) of OpenJDK that is installed. Oracle Java does this (at least for version 8) and is very nice. 

So, you may have something like this in the registry:

```
HLKM\
  Software\
    AdoptOpenJDK\
      JDK\
        - CurrentVersion=8.0.202.08
        8.0.202.08\
          MSI\
            -Path=C:\....
```

This would allow another MSI installer to interrogate what the latest version is.

**Comment by douph1** [comment]
>Currently, the MSI installed creates some registry keys to specify the JAVA_HOME for a specific version

It don't specify the JAVA_HOME but it record IF the option was checked at install time to allow repair and upgrade I think.

> It would be useful to have a CurrentVersion key at the HKLM\SOFTWARE$(var.ProductManufacturer)$(var.ProductCategory) level which tells what the current latest installed version (default version) of OpenJDK that is installed

There may be several latest versions at the same time:
The last JRE8-openj9,  the latest JDK11-hotspot etc 
 
Wich one put on CurrentVersion ? If we (dont) check the box during install to put enable JAVA_HOME and/or PATH ?

>This would allow another MSI installer to interrogate what the latest version is.
Which MSI installer interrogate it ? Adopt one ? what for ?

**Comment by slide** [comment]
For instance I am working on a new installer for Jenkins, I would like to be able to determine JAVA_HOME from the registry when I look for AdoptOpenJDK.

**Comment by douph1** [comment]
see https://github.com/AdoptOpenJDK/openjdk-installer/issues/64
