### ISSUE TITLE
Implement Code Signing for MSI installer

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-installer#7]

**Comment by alexhass** [comment]
What is needed here?

**Comment by karianna** [comment]
I think we need to get the installer installed on a windows host that can execute the code signing.  We have the https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/windows.p12 cert (not sure if it's still valid).

**Comment by alexhass** [comment]
First we should get the installer deployed. Than it is just 1 line in the batch files to enable the signing.

Without the private key password I cannot test the windows cert.

**Comment by alexhass** [comment]
Not yet

**Comment by gdams** [comment]
closing
