### ISSUE TITLE
WinRun4J launcher doesn't detect AdoptOpenJDK

### ISSUE THREAD

**Issue by xtbe** [AdoptOpenJDK/openjdk-installer#77]
OS : Windows 10 Enterprise b1809
AdoptOpenJDK build: 1.8.0_202_b08 (x64) (installed via MSI installer)
Java software to run: SQLWorkbench (http://www.sql-workbench.net/, http://www.sql-workbench.eu/)

Launching JAR via double-click on JAR : sqlworkbench.jar - OK
Launching JAR with CLI: java -jar sqlworkbench.jar - OK
Launch via EXE : SQLWorkbenhc64.exe Error - No suitable Java version could found. Please make sure you hava 64-bit Java 8 installed

SQLWorkbench64.exe/SQLWorkbench.exe are launchers which are based on WinRun4J (http://winrun4j.sourceforge.net/). It appears this launcher doesn't detect 
AdoptOpenJDK properly probably due to a missing registry entry.

Screenshot of the error:
![image](https://user-images.githubusercontent.com/909796/54843512-c269c480-4cd4-11e9-9965-8fa7ce9c52f2.png)

**Comment by karianna** [comment]
Do you know which entry http://winrun4j.sourceforge.net/ is looking for? Is it hardcoded to Oracle Java or?

**Comment by douph1** [comment]
https://github.com/poidasmith/winrun4j/blob/master/WinRun4J/src/java/VM.cpp

**Comment by douph1** [comment]
must be fixed for next installer by https://github.com/AdoptOpenJDK/openjdk-installer/pull/84
re-open if needed
