### ISSUE TITLE
How to install openjdk 8 in mac?

### ISSUE THREAD

**Issue by cchunduri** [AdoptOpenJDK/openjdk-installer#78]
Hi,

I've installed AdoptJDK 8 using pkg installer. Below is the name of the installer,
**OpenJDK8U-jdk_x64_mac_hotspot_8u202b08 00-46-43-545.pkg**

I want to install JDK 11 by uninstalling JDK 8, Could you please help me to uninstall OpenJDK 8 from my mac.

**Comment by gdams** [comment]
our jdk11 installer is designed to not overwrite jdk8 as many users wish to have this in parallel. If you wish to uninstall the jdk8 pkg I would suggest that you take a look at https://wincent.com/wiki/Uninstalling_packages_(.pkg_files)_on_Mac_OS_X
