### ISSUE TITLE
Replace MSI GPLv2 license with the GPLv2+CE for Hotspot derivative and check Eclipse OpenJ9 derivative.

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-installer#8]

**Comment by alexhass** [comment]
Should I convert https://github.com/eclipse/openj9/blob/master/LICENSE to RTF file? Not sure this is correct.

**Comment by karianna** [comment]
@alexhass The Eclipse OpenJ9 build will likely need that file yes.  The Hotspot build should have the GPLv2+CE (http://openjdk.java.net/legal/gplv2+ce.html)

**Comment by alexhass** [comment]
https://github.com/AdoptOpenJDK/openjdk-installer/pull/9

**Comment by alexhass** [comment]
Added OpenJ9 license
