### ISSUE TITLE
create_installer_windows error renaming msi file

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-installer#83]
openjdk8-openj9 Windows milestone 1 build fails in the create_installer_windows job with
```
mv OpenJDK8-jdk_x86-32_windows_openj9-8.0.212.01.msi OpenJDK8U-jdk_x86-32_windows_openj9_jdk8u212-b01_openj9-0.14.0-m1.msi OpenJDK8U-jre_x86-32_windows_openj9_jdk8u212-b01_openj9-0.14.0-m1.msi
mv: target 'OpenJDK8U-jre_x86-32_windows_openj9_jdk8u212-b01_openj9-0.14.0-m1.msi' is not a directory
Build step 'Execute shell' marked build as failure
```
Looks like mv has three arguments instead of two?

See job: https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/284/console

**Comment by douph1** [comment]
@lumpfish , are you able to trigger new build with same options (because job 284 is gone)
(openjdk8-openj9 Windows milestone 1)
If yes, you can run it, I have modified the shell script wich rename msi

**Comment by lumpfish** [comment]
Thanks @douph1 - I will resubmit.

**Comment by lumpfish** [comment]
@douph1 - different error now unfortunately:
```
+ for FILE in *.msi
+ case $FILE in
+ mv OpenJDK8U-jre_x86-32_windows_openj9_jdk8u212-b01_openj9-0.14.0-m1.msi OpenJDK8U-jre_x86-32_windows_openj9_jdk8u212-b01_openj9-0.14.0-m1.msi
mv: 'OpenJDK8U-jre_x86-32_windows_openj9_jdk8u212-b01_openj9-0.14.0-m1.msi' and 'OpenJDK8U-jre_x86-32_windows_openj9_jdk8u212-b01_openj9-0.14.0-m1.msi' are the same file
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE
```
Job is at: https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/303/console

**Comment by gdams** [comment]
@lumpfish please kick the job off again. Think I've fixed it.

**Comment by douph1** [comment]
build ok https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/324/console
