### ISSUE TITLE
BSOD with Minecraft 1.13.2???

### ISSUE THREAD

**Issue by Leo40Git** [AdoptOpenJDK/openjdk-installer#89]
**Platform:** Windows 10 v1903 (OS Build 18362.53)
**Architecture:** 64-bit
**AdoptOpen version:** JRE 8u212-b03 (installer version)
**JVM:** HotSpot

Joining a world in Minecraft 1.13.2 causes the system to blue screen. Yeah, I dunno either.

### Steps to reproduce:

1. Download [MultiMC development version](https://multimc.org/) (this is the launcher I used, this probably happens with the vanilla launcher too though)
2. Create an instance for 1.13.2 (this may happen with other versions, haven't tested)
3. Launch that instance
4. In that instance, create a new world
5. Wait until the "Joining world..." text appears
6. RIP Windows

**Comment by tellison** [comment]
While we wait for the Windows experts to show up, I suspect that if they can't recreate it locally they will need some basic information about your machine and the crash, e.g.:
 - Is the Windows 10 box up to date with patches? 
 - Can you provide the Stop error code?
 - Do you have a mini dump if they ask for it?

**Comment by Leo40Git** [comment]
* I'm using the "Slow" Insider setting.
* I didn't capture it, but I could probably repeat the crash and grab it.
* I don't think my laptop is currently configured to do that...

Guess I'm gonna go bluescreen my laptop, yay...

**Comment by Leo40Git** [comment]
...it worked fine this time?!?! Even though literally nothing changed?!?!

**Comment by Leo40Git** [comment]
Well whatever, turns out my laptop *was* configured to make minidumps when the BSOD happened:
https://www.dropbox.com/s/9ii2h9ddvzrxec6/AdoptOpenJDK%20MC1.13.2%20minidump%20files.zip?dl=0

**Comment by douph1** [comment]
The two minidump says the same things ... and it seems not related to AdoptOpenJDK

0: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

CRITICAL_STRUCTURE_CORRUPTION (109)
This bugcheck is generated when the kernel detects that critical kernel code or
data have been corrupted. There are generally three causes for a corruption:
1) A driver has inadvertently or deliberately modified critical kernel code
 or data. See http://www.microsoft.com/whdc/driver/kernel/64bitPatching.mspx
2) A developer attempted to set a normal kernel breakpoint using a kernel
 debugger that was not attached when the system was booted. Normal breakpoints,
 "bp", can only be set if the debugger is attached at boot time. Hardware
 breakpoints, "ba", can be set at any time.
3) A hardware corruption occurred, e.g. failing RAM holding kernel code or data.

**Comment by karianna** [comment]
Yep - looks like a hardware corruption.  I close this unless we get repeated test cases.  Thanks all for the investigation!!
