### ISSUE TITLE
How to configure unattended MSI install to use "write registry keys" option?

### ISSUE THREAD

**Issue by bauinformatiker** [AdoptOpenJDK/openjdk-installer#97]
The MSI installer is capable to write some registriy keys in Windows, e.g.

HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment
    CurrentVersion    REG_SZ    1.8

I only can enable this feature when using the GUI-Installer of the MSI file. I'm searching for the command line switch to enable this feature. Is there any docu about the cmd line installation of AdoptOpenJDK?

**Comment by gdams** [comment]
Take a look at https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/wix/README.md#features-available

In principle you would run:

`msiexec /i OpenJDK8-jdk_xxx.msi ADDLOCAL=FeatureOracleJavaSoft,<any other features>`

FYI when using ADDLOCAL only the features you specify are installed so so if you still want java to be in your PATH you'll have to specify that feature too.
